In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os

os.listdir('/content/drive/MyDrive/DATASETS')
zip_path = "/content/drive/MyDrive/DATASETS/IOTC-2026-WPTT28-DATA03_CE.zip"

In [3]:
import zipfile
import pandas as pd

with zipfile.ZipFile(zip_path, 'r') as z:
    with z.open("IOTC-2026-WPTT28-DATA03_CA.csv") as f:
        catch_df = pd.read_csv(f)

print(catch_df.shape)

(912678, 31)

In [4]:
for col in ["FLEET_CODE", "FLEET", "FISHERY_TYPE_CODE", "FISHERY_TYPE"]:
    print("\n==========", col, "==========")
    print(catch_df[col].value_counts().head(30))

========== FLEET_CODE ==========
FLEET_CODE
TWN      170066
EUESP    133446
SYC      112629
JPN      105556
EUFRA     99587
MDV       57478
LKA       34758
KOR       34630
NEIPS     27447
CHN       22782
IDN       20919
MUS       20098
EUREU     15523
NEISU     10467
EUMYT      6978
ZAF        5527
PHL        5045
AUS        3937
OMN        3604
THA        3453
IRN        3265
MYS        2858
SUN        1514
EUPRT      1433
TZA        1404
KEN        1399
IND        1291
COM        1029
NEICE       962
EUITA       779
Name: count, dtype: int64

========== FLEET ==========
FLEET
Taiwan,China                   170066
EU (Spain)                     133446
Seychelles                     112629
Japan                          105556
EU (France)                     99587
Maldives                        57478
Sri Lanka                       34758
Republic of Korea               34630
NEI (other)                     27447
China                           22782
Indonesia                       20919
Mauritius                       20098
EU (France,Réunion)             15523
NEI (ex-Soviet Union)           10467
EU (France,Mayotte)              6978
South Africa                     5527
Philippines                      5045
Australia                        3937
Sultanate of Oman                3604
Thailand                         3453
I. R. Iran                       3265
Malaysia                         2858
Soviet Union                     1514
EU (Portugal)                    1433
United republic of Tanzania      1404
Kenya                            1399
India                            1291
Comoros                          1029
NEI (fresh)                       962
EU (Italy)                        779
Name: count, dtype: int64

========== FISHERY_TYPE_CODE ==========
FISHERY_TYPE_CODE
IND    834673
ART     78005
Name: count, dtype: int64

========== FISHERY_TYPE ==========
FISHERY_TYPE
Industrial fisheries    834673
Artisanal fisheries      78005
Name: count, dtype: int64

In [5]:
ind_rows = catch_df[catch_df["FLEET_CODE"] == "IND"]

print("Rows with FLEET_CODE = IND:", len(ind_rows))

print("\nFleet names:")
print(ind_rows["FLEET"].value_counts())

print("\nSample:")
print(ind_rows[[
    "YEAR",
    "MONTH_START",
    "FISHING_GROUND_CODE",
    "FLEET_CODE",
    "FLEET",
    "SPECIES"
]].head(20))

Rows with FLEET_CODE = IND: 1291

Fleet names:
FLEET
India    1291
Name: count, dtype: int64

Sample:
       YEAR  MONTH_START  FISHING_GROUND_CODE FLEET_CODE  FLEET  \
52506  1976            1              6105075        IND  India
52870  1976            2              6105075        IND  India
53205  1976            3              6105075        IND  India
53492  1976            4              6105075        IND  India
53736  1976            5              6105075        IND  India
53995  1976            6              6105075        IND  India
53996  1976            6              6105075        IND  India
54251  1976            7              6105075        IND  India
54252  1976            7              6105075        IND  India
54517  1976            8              6105075        IND  India
54518  1976            8              6105075        IND  India
54799  1976            9              6105075        IND  India
54800  1976            9              6105075        IND  India
55057  1976           10              6105075        IND  India
55279  1976           11              6105075        IND  India
55508  1976           12              6105075        IND  India
55719  1977            1              6105075        IND  India
55720  1977            1              6105075        IND  India
55963  1977            2              6105075        IND  India
55964  1977            2              6105075        IND  India

              SPECIES
52506  Yellowfin tuna
52870  Yellowfin tuna
53205  Yellowfin tuna
53492  Yellowfin tuna
53736  Yellowfin tuna
53995  Yellowfin tuna
53996  Yellowfin tuna
54251  Yellowfin tuna
54252  Yellowfin tuna
54517  Yellowfin tuna
54518  Yellowfin tuna
54799  Yellowfin tuna
54800  Yellowfin tuna
55057  Yellowfin tuna
55279  Yellowfin tuna
55508  Yellowfin tuna
55719  Yellowfin tuna
55720  Yellowfin tuna
55963  Yellowfin tuna
55964  Yellowfin tuna

In [6]:
print("Number of species:", ind_rows["SPECIES"].nunique())

print("\nSpecies:")
print(ind_rows["SPECIES"].value_counts())

Number of species: 3

Species:
SPECIES
Yellowfin tuna    933
Skipjack tuna     308
Bigeye tuna        50
Name: count, dtype: int64

In [7]:
print("\nYears:")
print(ind_rows["YEAR"].min(), "to", ind_rows["YEAR"].max())

print("\nFishing grounds:")
print("Number of fishing grounds:", ind_rows["FISHING_GROUND_CODE"].nunique())
print(ind_rows["FISHING_GROUND_CODE"].value_counts().head(30))

Years:
1976 to 2021

Fishing grounds:
Number of fishing grounds: 62
FISHING_GROUND_CODE
6105075    444
6110090     60
6115080     53
6105090     52
6115085     49
5110080     47
6110080     44
9100020     41
9100080     40
5115080     39
5110090     33
6115070     27
6110085     26
6110070     25
6115065     24
5115085     21
5110070     21
6120065     20
5115070     17
5115065     15
5114067     15
6110095     11
5115066     10
5105090     10
5105071      9
5110071      9
6115090      9
5120065      9
6105070      8
5119067      7
Name: count, dtype: int64

In [8]:
with zipfile.ZipFile(zip_path, 'r') as z:
    with z.open("IOTC-2026-WPTT28-DATA03_EF.csv") as f:
        effort_df = pd.read_csv(f)

print(effort_df.shape)
print(effort_df.columns.tolist())
effort_df.head()

(692940, 17)
['YEAR', 'MONTH_START', 'MONTH_END', 'FISHING_GROUND_CODE', 'FLEET_CODE', 'FLEET', 'FISHERY_TYPE_CODE', 'FISHERY_TYPE', 'FISHERY_GROUP_CODE', 'FISHERY_GROUP', 'FISHERY_CODE', 'FISHERY', 'GEAR_CODE', 'GEAR', 'SCHOOL_TYPE_CODE', 'EFFORT_UNIT_CODE', 'EFFORT']

,YEAR,MONTH_START,MONTH_END,FISHING_GROUND_CODE,FLEET_CODE,FLEET,FISHERY_TYPE_CODE,FISHERY_TYPE,FISHERY_GROUP_CODE,FISHERY_GROUP,FISHERY_CODE,FISHERY,GEAR_CODE,GEAR,SCHOOL_TYPE_CODE,EFFORT_UNIT_CODE,EFFORT
0,1952,11,11,6210115,JPN,Japan,IND,Industrial fisheries,LL,Longline,LLD,Longline | Deep-freezing,LL,Longline (deep-freezing),UNCL,HOOKS,210196.0
1,1952,11,11,6210120,JPN,Japan,IND,Industrial fisheries,LL,Longline,LLD,Longline | Deep-freezing,LL,Longline (deep-freezing),UNCL,HOOKS,212089.0
2,1952,11,11,6215115,JPN,Japan,IND,Industrial fisheries,LL,Longline,LLD,Longline | Deep-freezing,LL,Longline (deep-freezing),UNCL,HOOKS,49305.0
3,1952,12,12,6210115,JPN,Japan,IND,Industrial fisheries,LL,Longline,LLD,Longline | Deep-freezing,LL,Longline (deep-freezing),UNCL,HOOKS,70480.0
4,1952,12,12,6210120,JPN,Japan,IND,Industrial fisheries,LL,Longline,LLD,Longline | Deep-freezing,LL,Longline (deep-freezing),UNCL,HOOKS,403413.0

In [9]:
for col in ["FLEET_CODE", "FLEET", "YEAR", "MONTH_START",
            "FISHING_GROUND_CODE", "EFFORT"]:
    if col in effort_df.columns:
        print("\n==========", col, "==========")
        print(effort_df[col].value_counts().head(15))

========== FLEET_CODE ==========
FLEET_CODE
EUESP    145110
EUFRA    138970
SYC       95281
JPN       54315
TWN       43924
MDV       37772
NEIPS     36810
LKA       26862
KOR       17445
IDN       14414
EUMYT     13479
MUS        9373
EUREU      9268
CHN        6203
NEISU      6134
Name: count, dtype: int64

========== FLEET ==========
FLEET
EU (Spain)               145110
EU (France)              138970
Seychelles                95281
Japan                     54315
Taiwan,China              43924
Maldives                  37772
NEI (other)               36810
Sri Lanka                 26862
Republic of Korea         17445
Indonesia                 14414
EU (France,Mayotte)       13479
Mauritius                  9373
EU (France,Réunion)        9268
China                      6203
NEI (ex-Soviet Union)      6134
Name: count, dtype: int64

========== YEAR ==========
YEAR
2024    28253
2025    25801
2023    25108
2007    21135
2013    20655
2002    20580
2017    20184
2008    19731
2001    19486
2006    19473
2000    18558
2009    18369
1998    18252
2003    18127
2012    17556
Name: count, dtype: int64

========== MONTH_START ==========
MONTH_START
11    64553
10    62589
3     59360
9     58817
12    58018
8     57395
5     57309
1     57114
4     55781
2     55417
7     53592
6     52995
Name: count, dtype: int64

========== FISHING_GROUND_CODE ==========
FISHING_GROUND_CODE
5204055    3741
5203053    2385
5100056    2236
5203052    2225
5204052    2211
5202054    2176
5204053    2170
5203054    2163
5202053    2113
5105072    2109
5203055    2108
5104073    2089
5203051    2087
5200055    2082
5202052    2054
Name: count, dtype: int64

========== EFFORT ==========
EFFORT
24.0    52979
1.0     47286
2.0     20598
12.1    19602
48.0    17541
12.0    17325
3.0     11449
72.0     8174
12.2     8152
4.0      8121
11.9     7354
12.3     6636
5.0      5280
11.8     4963
6.0      4952
Name: count, dtype: int64

In [10]:
ind_effort = effort_df[effort_df["FLEET_CODE"] == "IND"].copy()

print("Indian effort records:", len(ind_effort))

print("\nYears:")
print(ind_effort["YEAR"].min(), "to", ind_effort["YEAR"].max())

print("\nFishing grounds:")
print(ind_effort["FISHING_GROUND_CODE"].nunique())

print("\nEffort units:")
print(ind_effort["EFFORT_UNIT_CODE"].value_counts())

print("\nGear:")
print(ind_effort["GEAR"].value_counts().head(20))

Indian effort records: 1196

Years:
1976 to 2021

Fishing grounds:
69

Effort units:
EFFORT_UNIT_CODE
HOOKS    813
TRIPS    335
DAYS      48
Name: count, dtype: int64

Gear:
GEAR
Longline (exploratory)      723
Troll line                  177
Baitboat                    158
Longline (deep-freezing)     90
Gillnet                      36
Handline                     12
Name: count, dtype: int64

In [11]:
print("\nIndian effort sample:")
display(ind_effort.head(10))

Indian effort sample:

,YEAR,MONTH_START,MONTH_END,FISHING_GROUND_CODE,FLEET_CODE,FLEET,FISHERY_TYPE_CODE,FISHERY_TYPE,FISHERY_GROUP_CODE,FISHERY_GROUP,FISHERY_CODE,FISHERY,GEAR_CODE,GEAR,SCHOOL_TYPE_CODE,EFFORT_UNIT_CODE,EFFORT
23259,1976,1,1,6105075,IND,India,ART,Artisanal fisheries,BB,Baitboat,BB,Baitboat,BB,Baitboat,UNCL,TRIPS,195.0
23260,1976,1,1,6105075,IND,India,ART,Artisanal fisheries,LI,Line,LIT,Line | Trolling,TROL,Troll line,UNCL,TRIPS,4.0
23429,1976,2,2,6105075,IND,India,ART,Artisanal fisheries,BB,Baitboat,BB,Baitboat,BB,Baitboat,UNCL,TRIPS,147.0
23430,1976,2,2,6105075,IND,India,ART,Artisanal fisheries,LI,Line,LIT,Line | Trolling,TROL,Troll line,UNCL,TRIPS,6.0
23591,1976,3,3,6105075,IND,India,ART,Artisanal fisheries,BB,Baitboat,BB,Baitboat,BB,Baitboat,UNCL,TRIPS,194.0
23592,1976,3,3,6105075,IND,India,ART,Artisanal fisheries,LI,Line,LIT,Line | Trolling,TROL,Troll line,UNCL,TRIPS,5.0
23725,1976,4,4,6105075,IND,India,ART,Artisanal fisheries,BB,Baitboat,BB,Baitboat,BB,Baitboat,UNCL,TRIPS,193.0
23726,1976,4,4,6105075,IND,India,ART,Artisanal fisheries,LI,Line,LIT,Line | Trolling,TROL,Troll line,UNCL,TRIPS,3.0
23853,1976,5,5,6105075,IND,India,ART,Artisanal fisheries,BB,Baitboat,BB,Baitboat,BB,Baitboat,UNCL,TRIPS,83.0
23854,1976,5,5,6105075,IND,India,ART,Artisanal fisheries,LI,Line,LIT,Line | Trolling,TROL,Troll line,UNCL,TRIPS,4.0

In [12]:
print("Catch-related columns:")
for col in catch_df.columns:
    print(col)

Catch-related columns:
YEAR
MONTH_START
MONTH_END
FISHING_GROUND_CODE
FLEET_CODE
FLEET
FISHERY_TYPE_CODE
FISHERY_TYPE
FISHERY_GROUP_CODE
FISHERY_GROUP
FISHERY_CODE
FISHERY
GEAR_CODE
GEAR
CATCH_SCHOOL_TYPE_CODE
SPECIES_CATEGORY
SPECIES_CATEGORY_CODE
SPECIES_CODE
SPECIES
SPECIES_SCIENTIFIC
IS_IOTC_SPECIES
IS_SPECIES_AGGREGATE
IS_SSI
FATE_TYPE_CODE
FATE_TYPE
FATE_CODE
FATE
RAISE_CODE
RAISING
CATCH_UNIT_CODE
CATCH

In [13]:
print("\nColumns shared by CATCH and EFFORT:")

common_columns = sorted(set(catch_df.columns) & set(effort_df.columns))

for col in common_columns:
    print(col)

Columns shared by CATCH and EFFORT:
FISHERY
FISHERY_CODE
FISHERY_GROUP
FISHERY_GROUP_CODE
FISHERY_TYPE
FISHERY_TYPE_CODE
FISHING_GROUND_CODE
FLEET
FLEET_CODE
GEAR
GEAR_CODE
MONTH_END
MONTH_START
YEAR

In [14]:
merge_keys = [
    "YEAR",
    "MONTH_START",
    "MONTH_END",
    "FISHING_GROUND_CODE",
    "FLEET_CODE",
    "FISHERY_TYPE_CODE",
    "FISHERY_GROUP_CODE",
    "FISHERY_CODE",
    "GEAR_CODE"
]

print("Testing effort uniqueness...")

duplicates = (
    ind_effort
    .groupby(merge_keys)
    .size()
    .sort_values(ascending=False)
)

print(duplicates.head(20))

Testing effort uniqueness...
YEAR  MONTH_START  MONTH_END  FISHING_GROUND_CODE  FLEET_CODE  FISHERY_TYPE_CODE  FISHERY_GROUP_CODE  FISHERY_CODE  GEAR_CODE
2021  12           12         5115081              IND         IND                LL                  LLD           LLEX         1
1976  1            1          6105075              IND         ART                BB                  BB            BB           1
                                                                                  LI                  LIT           TROL         1
      2            2          6105075              IND         ART                BB                  BB            BB           1
                                                                                  LI                  LIT           TROL         1
      3            3          6105075              IND         ART                BB                  BB            BB           1
                                                                                  LI                  LIT           TROL         1
      4            4          6105075              IND         ART                BB                  BB            BB           1
                                                                                  LI                  LIT           TROL         1
      5            5          6105075              IND         ART                BB                  BB            BB           1
                                                                                  LI                  LIT           TROL         1
      6            6          6105075              IND         ART                BB                  BB            BB           1
2020  10           10         6115085              IND         IND                LL                  LLD           LLEX         1
      3            3          6115085              IND         IND                LL                  LLD           LLEX         1
      2            2          6115080              IND         IND                LL                  LLD           LLEX         1
      1            1          6115085              IND         IND                LL                  LLD           LLEX         1
2018  12           12         6115085              IND         IND                LL                  LLD           LLEX         1
                              6115080              IND         IND                LL                  LLD           LLEX         1
                              6115075              IND         IND                LL                  LLD           LLEX         1
                              6115070              IND         IND                LL                  LLD           LLEX         1
dtype: int64

In [15]:
print("Total effort rows:", len(ind_effort))
print("Unique combinations:", len(duplicates))
print("Duplicate combinations:", (duplicates > 1).sum())

Total effort rows: 1196
Unique combinations: 1196
Duplicate combinations: 0

In [16]:
catch_ind = catch_df[catch_df["FLEET_CODE"] == "IND"].copy()

print("Indian catch records:", len(catch_ind))

print("\nSpecies:")
print(catch_ind["SPECIES"].value_counts())

print("\nEffort units:")
print(catch_ind["GEAR_CODE"].value_counts())

Indian catch records: 1291

Species:
SPECIES
Yellowfin tuna    933
Skipjack tuna     308
Bigeye tuna        50
Name: count, dtype: int64

Effort units:
GEAR_CODE
LLEX    761
TROL    212
BB      208
LL       90
GILL     18
HAND      2
Name: count, dtype: int64

In [17]:
print("\nCatch columns at the end:")
print(catch_ind.columns[-10:].tolist())

Catch columns at the end:
['IS_SPECIES_AGGREGATE', 'IS_SSI', 'FATE_TYPE_CODE', 'FATE_TYPE', 'FATE_CODE', 'FATE', 'RAISE_CODE', 'RAISING', 'CATCH_UNIT_CODE', 'CATCH']

In [18]:
catch_keys = [
    "YEAR",
    "MONTH_START",
    "MONTH_END",
    "FISHING_GROUND_CODE",
    "FLEET_CODE",
    "FISHERY_TYPE_CODE",
    "FISHERY_GROUP_CODE",
    "FISHERY_CODE",
    "GEAR_CODE"
]

catch_group_sizes = catch_ind.groupby(catch_keys).size()

print("Total catch rows:", len(catch_ind))
print("Unique catch combinations:", len(catch_group_sizes))
print("Combinations containing multiple species:",
      (catch_group_sizes > 1).sum())

Total catch rows: 1291
Unique catch combinations: 980
Combinations containing multiple species: 300

In [19]:
print("CATCH UNITS")
print(catch_ind["CATCH_UNIT_CODE"].value_counts())

print("\nEFFORT UNITS")
print(ind_effort["EFFORT_UNIT_CODE"].value_counts())

CATCH UNITS
CATCH_UNIT_CODE
MT    1291
Name: count, dtype: int64

EFFORT UNITS
EFFORT_UNIT_CODE
HOOKS    813
TRIPS    335
DAYS      48
Name: count, dtype: int64

In [20]:
print("\nCatch range:")
print(catch_ind["CATCH"].describe())

print("\nEffort range:")
print(ind_effort["EFFORT"].describe())

Catch range:
count    1291.000000
mean       11.750960
std        81.753432
min         0.001000
25%         0.048000
50%         0.270000
75%         2.043500
max      2618.230000
Name: CATCH, dtype: float64

Effort range:
count    1.196000e+03
mean     3.703003e+04
std      2.056093e+05
min      1.000000e+00
25%      3.500000e+02
50%      2.072500e+03
75%      6.400000e+03
max      4.145045e+06
Name: EFFORT, dtype: float64

In [21]:
# Check how many Indian catch observations have matching
# Indian effort observations on the same fishing dimensions.

catch_keys = [
    "YEAR",
    "MONTH_START",
    "MONTH_END",
    "FISHING_GROUND_CODE",
    "FLEET_CODE",
    "FISHERY_TYPE_CODE",
    "FISHERY_GROUP_CODE",
    "FISHERY_CODE",
    "GEAR_CODE"
]

effort_keys = catch_keys + ["EFFORT_UNIT_CODE"]

# Unique effort combinations
effort_lookup = ind_effort[catch_keys].drop_duplicates()

# Check matches
test = catch_ind.merge(
    effort_lookup,
    on=catch_keys,
    how="left",
    indicator=True
)

print("Total Indian catch rows:", len(test))
print("\nMatching catch rows:")
print(test["_merge"].value_counts())

print("\nPercentage matched:")
print(test["_merge"].value_counts(normalize=True) * 100)

Total Indian catch rows: 1291

Matching catch rows:
_merge
both          1291
left_only        0
right_only       0
Name: count, dtype: int64

Percentage matched:
_merge
both          100.0
left_only       0.0
right_only      0.0
Name: proportion, dtype: float64

In [22]:
pd.crosstab(
    ind_effort["GEAR"],
    ind_effort["EFFORT_UNIT_CODE"]
)

EFFORT_UNIT_CODE          DAYS  HOOKS  TRIPS
GEAR
Baitboat                     0      0    158
Gillnet                     36      0      0
Handline                    12      0      0
Longline (deep-freezing)     0     90      0
Longline (exploratory)       0    723      0
Troll line                   0      0    177

In [23]:
# Common dimensions between catch and effort
keys = [
    "YEAR",
    "MONTH_START",
    "MONTH_END",
    "FISHING_GROUND_CODE",
    "FLEET_CODE",
    "FISHERY_TYPE_CODE",
    "FISHERY_GROUP_CODE",
    "FISHERY_CODE",
    "GEAR_CODE"
]

# 1. Aggregate all species caught at each fishing operation
catch_agg = (
    catch_ind
    .groupby(keys, as_index=False)
    .agg(TOTAL_CATCH_MT=("CATCH", "sum"))
)

# 2. Keep the corresponding effort observation
effort_clean = (
    ind_effort[
        keys + ["GEAR", "EFFORT_UNIT_CODE", "EFFORT"]
    ]
    .copy()
)

# 3. Merge catch + effort
fish_df = catch_agg.merge(
    effort_clean,
    on=keys,
    how="inner"
)

# 4. Calculate CPUE
fish_df["CPUE"] = fish_df["TOTAL_CATCH_MT"] / fish_df["EFFORT"]

print("Final rows:", len(fish_df))
print("\nColumns:")
print(fish_df.columns.tolist())

print("\nSample:")
display(fish_df.head(10))

Final rows: 980

Columns:
['YEAR', 'MONTH_START', 'MONTH_END', 'FISHING_GROUND_CODE', 'FLEET_CODE', 'FISHERY_TYPE_CODE', 'FISHERY_GROUP_CODE', 'FISHERY_CODE', 'GEAR_CODE', 'TOTAL_CATCH_MT', 'GEAR', 'EFFORT_UNIT_CODE', 'EFFORT', 'CPUE']

Sample:

,YEAR,MONTH_START,MONTH_END,FISHING_GROUND_CODE,FLEET_CODE,FISHERY_TYPE_CODE,FISHERY_GROUP_CODE,FISHERY_CODE,GEAR_CODE,TOTAL_CATCH_MT,GEAR,EFFORT_UNIT_CODE,EFFORT,CPUE
0,1976,1,1,6105075,IND,ART,BB,BB,BB,3.202,Baitboat,TRIPS,195.0,0.016421
1,1976,2,2,6105075,IND,ART,BB,BB,BB,4.559,Baitboat,TRIPS,147.0,0.031014
2,1976,3,3,6105075,IND,ART,BB,BB,BB,4.320,Baitboat,TRIPS,194.0,0.022268
3,1976,4,4,6105075,IND,ART,BB,BB,BB,0.772,Baitboat,TRIPS,193.0,0.004000
4,1976,5,5,6105075,IND,ART,BB,BB,BB,0.203,Baitboat,TRIPS,83.0,0.002446
5,1976,6,6,6105075,IND,ART,BB,BB,BB,0.047,Baitboat,TRIPS,53.0,0.000887
6,1976,6,6,6105075,IND,ART,LI,LIT,TROL,0.031,Troll line,TRIPS,6.0,0.005167
7,1976,7,7,6105075,IND,ART,BB,BB,BB,0.005,Baitboat,TRIPS,18.0,0.000278
8,1976,7,7,6105075,IND,ART,LI,LIT,TROL,0.257,Troll line,TRIPS,9.0,0.028556
9,1976,8,8,6105075,IND,ART,BB,BB,BB,0.033,Baitboat,TRIPS,4.0,0.008250

In [24]:
print(fish_df[[
    "GEAR",
    "EFFORT_UNIT_CODE",
    "TOTAL_CATCH_MT",
    "EFFORT",
    "CPUE"
]].describe(include="all"))

                          GEAR EFFORT_UNIT_CODE  TOTAL_CATCH_MT        EFFORT  \
count                      980              980      980.000000  9.800000e+02
unique                       6                3             NaN           NaN
top     Longline (exploratory)            HOOKS             NaN           NaN
freq                       559              648             NaN           NaN
mean                       NaN              NaN       15.480091  4.474774e+04
std                        NaN              NaN       95.307064  2.264318e+05
min                        NaN              NaN        0.001000  1.000000e+00
25%                        NaN              NaN        0.081000  2.007500e+02
50%                        NaN              NaN        0.390000  2.522500e+03
75%                        NaN              NaN        3.078750  7.500000e+03
max                        NaN              NaN     2627.500000  4.145045e+06

                CPUE
count   9.800000e+02
unique           NaN
top              NaN
freq             NaN
mean    1.660355e-02
std     4.687822e-02
min     3.174603e-07
25%     3.252500e-05
50%     1.187238e-04
75%     7.226585e-03
max     5.914615e-01

In [25]:
print(fish_df["FISHING_GROUND_CODE"].unique())

[6105075 6100075 6100080 6100085 6100090 6105065 6105070 6105085 6105090
 6110065 6110070 6110080 6110085 6110090 6115065 6115070 6115080 6115085
 6115090 6120065 6105095 6110095 6115095 9100080 9100020 5110090 5114067
 5115080 5115085 5119067 5105088 5110080 5115066 5120066 5115071 5110066
 5110071 5105071 5105076 5105093 5110085 5110088 5110093 5105080 5105090
 5110070 5115065 5115070 5120065 5105070 5110065 5114065 6115075 6120070
 6120085 6110075 5120070 5115082 5115075 5112080 5110075 5114082]

In [26]:
print(fish_df["FISHING_GROUND_CODE"].nunique())

62

In [27]:
grid_path = "/content/drive/MyDrive/DATASETS/IOTC_GRIDS_CE_SF_AR.gpkg"

In [28]:
import os

grid_path = "/content/drive/MyDrive/DATASETS/IOTC_GRIDS_CE_SF_AR.gpkg"

print(os.path.exists(grid_path))

True

In [29]:
import geopandas as gpd

grid_path = "/content/drive/MyDrive/DATASETS/IOTC_GRIDS_CE_SF_AR.gpkg"

# See what layers are inside the GPKG
layers = gpd.list_layers(grid_path)

print(layers)

                  name geometry_type
0  IOTC_GRIDS_CE_SF_AR  MultiPolygon

In [30]:
grid = gpd.read_file(
    grid_path,
    layer="IOTC_GRIDS_CE_SF_AR"
)

print("Shape:", grid.shape)
print("\nColumns:")
print(grid.columns.tolist())

print("\nFirst 5 rows:")
display(grid.head())

Shape: (6484, 9)

Columns:
['CODE', 'NAME_EN', 'NAME_FR', 'OCEAN_AREA', 'IO_AREA', 'IOTC_AREA', 'CENTER_LAT', 'CENTER_LON', 'geometry']

First 5 rows:

,CODE,NAME_EN,NAME_FR,OCEAN_AREA,IO_AREA,IOTC_AREA,CENTER_LAT,CENTER_LON,geometry
0,5100042,00° - 01° latitude North; 042° - 043° longitud...,00° - 01° latitude Nord; 042° - 043° longitude...,74.0,74.0,74.0,0.038704,42.965353,"MULTIPOLYGON (((42.89606 0, 42.9 0, 42.91667 0..."
1,5100043,00° - 01° latitude North; 043° - 044° longitud...,00° - 01° latitude Nord; 043° - 044° longitude...,7717.0,7717.0,7717.0,0.373420,43.625634,"MULTIPOLYGON (((43 0, 43.01667 0, 43.03333 0, ..."
2,5100044,00° - 01° latitude North; 044° - 045° longitud...,00° - 01° latitude Nord; 044° - 045° longitude...,12308.0,12308.0,12308.0,0.500000,44.500000,"MULTIPOLYGON (((44 0, 44.01667 0, 44.03333 0, ..."
3,5100045,00° - 01° latitude North; 045° - 046° longitud...,00° - 01° latitude Nord; 045° - 046° longitude...,12308.0,12308.0,12308.0,0.500000,45.500000,"MULTIPOLYGON (((45 0, 45.01667 0, 45.03333 0, ..."
4,5100046,00° - 01° latitude North; 046° - 047° longitud...,00° - 01° latitude Nord; 046° - 047° longitude...,12308.0,12308.0,12308.0,0.500000,46.500000,"MULTIPOLYGON (((46 0, 46.01667 0, 46.03333 0, ..."

In [31]:
# Convert both codes to strings so there are no datatype issues
fish_codes = set(fish_df["FISHING_GROUND_CODE"].astype(str))
grid_codes = set(grid["CODE"].astype(str))

matched = fish_codes.intersection(grid_codes)
missing = fish_codes - grid_codes

print("Fishing grounds in fish_df:", len(fish_codes))
print("Matched with GPKG:", len(matched))
print("Missing:", len(missing))

if missing:
    print("\nMissing codes:")
    print(sorted(missing))

Fishing grounds in fish_df: 62
Matched with GPKG: 58
Missing: 4

Missing codes:
['5115075', '6115075', '9100020', '9100080']

In [32]:
missing_codes = ["515075", "6115075", "9100020", "9100080"]

for code in missing_codes:
    print("\nCODE:", code)

    # Look for codes beginning similarly
    prefix = code[:3]
    matches = grid[grid["CODE"].astype(str).str.startswith(prefix)]

    print(matches[["CODE", "CENTER_LAT", "CENTER_LON"]].head(20).to_string(index=False))

fish_df = fish_df[fish_df["FISHING_GROUND_CODE"].isin(grid["CODE"])]

CODE: 515075
Empty DataFrame
Columns: [CODE, CENTER_LAT, CENTER_LON]
Index: []

CODE: 6115075
   CODE  CENTER_LAT  CENTER_LON
6110040   12.798557   43.334764
6110045   12.471330   47.633546
6110050   12.631054   52.653126
6110055   12.500000   57.500000
6110060   12.500000   62.500000
6110065   12.500000   67.500000
6110070   12.424875   72.399294
6110075   10.842759   76.452233
6110080   12.476727   82.554531
6110085   12.500000   87.500000
6110090   12.504149   92.494324
6110095   12.412717   96.701606
6115035   18.375107   39.016702
6115040   16.976694   41.140603
6115050   15.834361   53.528483
6115055   17.130387   57.834836
6115060   17.500000   62.500000
6115065   17.500000   67.500000
6115070   17.337561   71.614762
6115080   16.365458   83.268322

CODE: 9100020
Empty DataFrame
Columns: [CODE, CENTER_LAT, CENTER_LON]
Index: []

CODE: 9100080
Empty DataFrame
Columns: [CODE, CENTER_LAT, CENTER_LON]
Index: []

In [33]:
missing_codes = ["515075", "6115075", "9100020", "9100080"]

display(
    fish_df[
        fish_df["FISHING_GROUND_CODE"].astype(str).isin(missing_codes)
    ][[
        "FISHING_GROUND_CODE",
        "YEAR",
        "MONTH_START",
        "SPECIES" if "SPECIES" in fish_df.columns else "GEAR",
        "GEAR",
        "TOTAL_CATCH_MT",
        "EFFORT",
        "CPUE"
    ]].sort_values(["FISHING_GROUND_CODE", "YEAR", "MONTH_START"])
)

Empty DataFrame
Columns: [FISHING_GROUND_CODE, YEAR, MONTH_START, GEAR, GEAR, TOTAL_CATCH_MT, EFFORT, CPUE]
Index: []

In [34]:
for code in missing_codes:
    count = (fish_df["FISHING_GROUND_CODE"].astype(str) == code).sum()
    print(code, "→", count, "rows")

515075 → 0 rows
6115075 → 0 rows
9100020 → 0 rows
9100080 → 0 rows

In [35]:
print("Current fish_df shape:", fish_df.shape)
print("Current unique fishing grounds:", fish_df["FISHING_GROUND_CODE"].nunique())

print("\nCurrent fishing ground codes:")
print(sorted(fish_df["FISHING_GROUND_CODE"].astype(str).unique()))

Current fish_df shape: (0, 14)
Current unique fishing grounds: 0

Current fishing ground codes:
[]

In [36]:
print("catch_df:", catch_df.shape)
print("effort_df:", effort_df.shape)

print("\nIndia catch rows:")
print((catch_df["FLEET_CODE"] == "IND").sum())

print("India effort rows:")
print((effort_df["FLEET_CODE"] == "IND").sum())

catch_df: (912678, 31)
effort_df: (692940, 17)

India catch rows:
1291
India effort rows:
1196

In [37]:
# Filter India
india_catch = catch_df[catch_df["FLEET_CODE"] == "IND"].copy()
india_effort = effort_df[effort_df["FLEET_CODE"] == "IND"].copy()

# Keys that define the same fishing activity
merge_keys = [
    "YEAR",
    "MONTH_START",
    "MONTH_END",
    "FISHING_GROUND_CODE",
    "FLEET_CODE",
    "FISHERY_TYPE_CODE",
    "FISHERY_GROUP_CODE",
    "FISHERY_CODE",
    "GEAR_CODE"
]

# Aggregate catch
catch_agg = (
    india_catch
    .groupby(merge_keys, as_index=False)["CATCH"]
    .sum()
    .rename(columns={"CATCH": "TOTAL_CATCH_MT"})
)

# Keep only required effort information
effort_clean = india_effort[
    merge_keys + ["GEAR", "EFFORT_UNIT_CODE", "EFFORT"]
].copy()

# Merge catch + effort
fish_df = catch_agg.merge(
    effort_clean,
    on=merge_keys,
    how="inner"
)

# Calculate CPUE
fish_df["CPUE"] = (
    fish_df["TOTAL_CATCH_MT"] / fish_df["EFFORT"]
)

print("fish_df shape:", fish_df.shape)
print("Unique fishing grounds:", fish_df["FISHING_GROUND_CODE"].nunique())
print("Missing CPUE:", fish_df["CPUE"].isna().sum())

display(fish_df.head())

fish_df shape: (980, 14)
Unique fishing grounds: 62
Missing CPUE: 0

,YEAR,MONTH_START,MONTH_END,FISHING_GROUND_CODE,FLEET_CODE,FISHERY_TYPE_CODE,FISHERY_GROUP_CODE,FISHERY_CODE,GEAR_CODE,TOTAL_CATCH_MT,GEAR,EFFORT_UNIT_CODE,EFFORT,CPUE
0,1976,1,1,6105075,IND,ART,BB,BB,BB,3.202,Baitboat,TRIPS,195.0,0.016421
1,1976,2,2,6105075,IND,ART,BB,BB,BB,4.559,Baitboat,TRIPS,147.0,0.031014
2,1976,3,3,6105075,IND,ART,BB,BB,BB,4.320,Baitboat,TRIPS,194.0,0.022268
3,1976,4,4,6105075,IND,ART,BB,BB,BB,0.772,Baitboat,TRIPS,193.0,0.004000
4,1976,5,5,6105075,IND,ART,BB,BB,BB,0.203,Baitboat,TRIPS,83.0,0.002446

In [38]:
backup_path = "/content/drive/MyDrive/DATASETS/fish_df_iotc_india.csv"

fish_df.to_csv(backup_path, index=False)

print("Saved:", backup_path)

Saved: /content/drive/MyDrive/DATASETS/fish_df_iotc_india.csv

In [39]:
import os

print("Backup exists:", os.path.exists(backup_path))
print("File size (MB):", round(os.path.getsize(backup_path) / (1024**2), 2))

Backup exists: True
File size (MB): 0.09

In [40]:
# Prepare spatial reference for merging
grid_coords = grid[["CODE", "CENTER_LAT", "CENTER_LON"]].copy()

# Make sure both codes have the same type
grid_coords["CODE"] = grid_coords["CODE"].astype(str)
fish_df["FISHING_GROUND_CODE"] = fish_df["FISHING_GROUND_CODE"].astype(str)

# Merge coordinates into fish_df
fish_geo = fish_df.merge(
    grid_coords,
    left_on="FISHING_GROUND_CODE",
    right_on="CODE",
    how="left"
)

# Check result
print("Rows:", len(fish_geo))
print("Missing latitude:", fish_geo["CENTER_LAT"].isna().sum())
print("Missing longitude:", fish_geo["CENTER_LON"].isna().sum())

display(
    fish_geo[
        ["FISHING_GROUND_CODE", "YEAR", "MONTH_START",
         "CENTER_LAT", "CENTER_LON", "TOTAL_CATCH_MT", "CPUE"]
    ].head(10)
)

Rows: 980
Missing latitude: 55
Missing longitude: 55

,FISHING_GROUND_CODE,YEAR,MONTH_START,CENTER_LAT,CENTER_LON,TOTAL_CATCH_MT,CPUE
0,6105075,1976,1,7.184509,77.438964,3.202,0.016421
1,6105075,1976,2,7.184509,77.438964,4.559,0.031014
2,6105075,1976,3,7.184509,77.438964,4.320,0.022268
3,6105075,1976,4,7.184509,77.438964,0.772,0.004000
4,6105075,1976,5,7.184509,77.438964,0.203,0.002446
5,6105075,1976,6,7.184509,77.438964,0.047,0.000887
6,6105075,1976,6,7.184509,77.438964,0.031,0.005167
7,6105075,1976,7,7.184509,77.438964,0.005,0.000278
8,6105075,1976,7,7.184509,77.438964,0.257,0.028556
9,6105075,1976,8,7.184509,77.438964,0.033,0.008250

In [41]:
missing_geo = fish_geo[fish_geo["CENTER_LAT"].isna()]

print("Missing-coordinate rows:", len(missing_geo))

print("\nMissing fishing-ground codes:")
print(
    missing_geo["FISHING_GROUND_CODE"]
    .value_counts()
)

Missing-coordinate rows: 55

Missing fishing-ground codes:
FISHING_GROUND_CODE
9100020    25
9100080    23
6115075     6
5115075     1
Name: count, dtype: int64

In [42]:
# Keep only observations with valid geographic coordinates
fish_geo_valid = fish_geo.dropna(
    subset=["CENTER_LAT", "CENTER_LON"]
).copy()

print("Original observations:", len(fish_geo))
print("Spatially resolved:", len(fish_geo_valid))
print("Excluded due to missing coordinates:", len(fish_geo) - len(fish_geo_valid))

print("\nUnique fishing grounds:")
print(fish_geo_valid["FISHING_GROUND_CODE"].nunique())

Original observations: 980
Spatially resolved: 925
Excluded due to missing coordinates: 55

Unique fishing grounds:
58

In [43]:
spatial_path = "/content/drive/MyDrive/DATASETS/fish_geo_valid.csv"

fish_geo_valid.to_csv(spatial_path, index=False)

print("Saved:", spatial_path)

Saved: /content/drive/MyDrive/DATASETS/fish_geo_valid.csv

In [44]:
import os

print("Backup exists:", os.path.exists(spatial_path))
print("Size (MB):", round(os.path.getsize(spatial_path) / (1024**2), 2))

Backup exists: True
Size (MB): 0.12

In [45]:
import os

chl_path = "/content/drive/MyDrive/DATASETS/incois_oceansat2_datasets_cecb_07d5_7d07.csv"

print("Exists:", os.path.exists(chl_path))

if os.path.exists(chl_path):
    print("Size (MB):", round(os.path.getsize(chl_path) / (1024**2), 2))

Exists: True
Size (MB): 323.78

In [46]:
with open(chl_path, "r", encoding="utf-8", errors="ignore") as f:
    for _ in range(10):
        print(f.readline().rstrip())

time,latitude,longitude,CHL
UTC,degrees_north,degrees_east,mg/m3
2019-01-01T00:00:00Z,4.996724896438959,65.000949973398,0.6248304
2019-01-01T00:00:00Z,4.996724896438959,65.200926224053,0.5703326
2019-01-01T00:00:00Z,4.996724896438959,65.400902474708,0.5425869
2019-01-01T00:00:00Z,4.996724896438959,65.600878725363,NaN
2019-01-01T00:00:00Z,4.996724896438959,65.800854976018,0.5468126
2019-01-01T00:00:00Z,4.996724896438959,66.000831226673,NaN
2019-01-01T00:00:00Z,4.996724896438959,66.200807477328,NaN
2019-01-01T00:00:00Z,4.996724896438959,66.400783727983,0.5771064

In [47]:
print("Fishing data years:")
print(sorted(fish_geo_valid["YEAR"].unique()))

print("\nFishing observations by year:")
print(fish_geo_valid["YEAR"].value_counts().sort_index())

Fishing data years:
[np.int64(1976), np.int64(1977), np.int64(1978), np.int64(1979), np.int64(1980), np.int64(1981), np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2018), np.int64(2020), np.int64(2021)]

Fishing observations by year:
YEAR
1976    16
1977    20
1978    22
1979    29
1980    26
1981    27
1982    20
1983    21
1984    22
1985    21
1986    19
1987    18
1988    18
1989    24
1990    20
1991    29
1994     3
1995    28
1996    20
1997    18
2005    50
2006    42
2007    46
2008    40
2009    40
2010    44
2011    56
2012    39
2013    40
2014    22
2015    48
2018    25
2020     6
2021     6
Name: count, dtype: int64

In [48]:
print("Latitude range:",
      fish_geo_valid["CENTER_LAT"].min(),
      "to",
      fish_geo_valid["CENTER_LAT"].max())

print("Longitude range:",
      fish_geo_valid["CENTER_LON"].min(),
      "to",
      fish_geo_valid["CENTER_LON"].max())

Latitude range: 2.500000000000007 to 22.12616390623064
Longitude range: 65.5 to 97.19339630888105

In [49]:
# Check how much fishing data overlaps with the OCM period

overlap = fish_geo_valid[
    fish_geo_valid["YEAR"].isin([2019, 2020])
].copy()

print("2019–2020 fishing observations:", len(overlap))
print("Fishing grounds represented:", overlap["FISHING_GROUND_CODE"].nunique())

print("\nObservations by year:")
print(overlap["YEAR"].value_counts().sort_index())

print("\nCoordinates inside our OCM download area (5–24N, 65–95E):")

inside_ocm = overlap[
    overlap["CENTER_LAT"].between(5, 24) &
    overlap["CENTER_LON"].between(65, 95)
]

print("Inside OCM area:", len(inside_ocm))
print("Outside OCM area:", len(overlap) - len(inside_ocm))
print("Fishing grounds inside:", inside_ocm["FISHING_GROUND_CODE"].nunique())

2019–2020 fishing observations: 6
Fishing grounds represented: 2

Observations by year:
YEAR
2020    6
Name: count, dtype: int64

Coordinates inside our OCM download area (5–24N, 65–95E):
Inside OCM area: 6
Outside OCM area: 0
Fishing grounds inside: 2

In [50]:
modern_fish = fish_geo_valid[
    fish_geo_valid["YEAR"] >= 1998
].copy()

print("Observations from 1998 onward:", len(modern_fish))
print("Unique fishing grounds:", modern_fish["FISHING_GROUND_CODE"].nunique())

print("\nObservations by year:")
print(
    modern_fish["YEAR"]
    .value_counts()
    .sort_index()
)

Observations from 1998 onward: 504
Unique fishing grounds: 54

Observations by year:
YEAR
2005    50
2006    42
2007    46
2008    40
2009    40
2010    44
2011    56
2012    39
2013    40
2014    22
2015    48
2018    25
2020     6
2021     6
Name: count, dtype: int64

In [51]:
training_fish = fish_geo_valid[
    fish_geo_valid["YEAR"].between(2005, 2014)
].copy()

print("Training observations:", len(training_fish))
print("Unique fishing grounds:", training_fish["FISHING_GROUND_CODE"].nunique())
print("Years:", sorted(training_fish["YEAR"].unique()))

print("\nObservations by year:")
print(
    training_fish["YEAR"]
    .value_counts()
    .sort_index()
)

Training observations: 419
Unique fishing grounds: 45
Years: [np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014)]

Observations by year:
YEAR
2005    50
2006    42
2007    46
2008    40
2009    40
2010    44
2011    56
2012    39
2013    40
2014    22
Name: count, dtype: int64

In [52]:
import os

print(os.listdir("/content/drive/MyDrive/DATASETS"))

['IOTC-2026-WPTT28-DATA03_CE.zip', 'Marine Fish Landings in India - 2025.pdf', 'Marine Fish Landings in India - 2024.pdf', 'incois_oceansat2_datasets_cecb_07d5_7d07.csv', 'IOTC_GRIDS_CE_SF_AR.gpkg', 'fish_df_iotc_india.csv', 'fish_geo_valid.csv', 'incois_tmi_sst_2005_2014_indian_ocean.nc', 'fishing_ground_model_final.joblib']

In [53]:
import os

sst_path = "/content/drive/MyDrive/DATASETS/incois_tmi_sst_2005_2014_indian_ocean.nc"

sst_url = (
    "https://erddap.incois.gov.in/erddap/griddap/"
    "incois_tmi_3day_datasets.nc?"
    "SST"
    "[(2005-01-01T00:00:00Z):"
    "(2014-12-31T00:00:00Z)]"
    "[(2.25):1:(22.25)]"
    "[(65.25):1:(97.25)]"
)

print("Downloading SST subset...")
print("Destination:", sst_path)

!wget -q --show-progress -O "{sst_path}" "{sst_url}"

print("\nDownload complete.")
print("Exists:", os.path.exists(sst_path))

if os.path.exists(sst_path):
    print(
        "Size (MB):",
        round(os.path.getsize(sst_path) / (1024**2), 2)
    )

Downloading SST subset...
Destination: /content/drive/MyDrive/DATASETS/incois_tmi_sst_2005_2014_indian_ocean.nc

Download complete.
Exists: True
Size (MB): 0.0

In [54]:
import os

if os.path.exists(sst_path):
    os.remove(sst_path)

print("Empty file removed:", not os.path.exists(sst_path))

Empty file removed: True

In [55]:
import os

sst_path = "/content/drive/MyDrive/DATASETS/incois_tmi_sst_2005_2014_indian_ocean.nc"

if os.path.exists(sst_path):
    os.remove(sst_path)

print("Ready:", not os.path.exists(sst_path))

Ready: True

In [56]:
import requests

test_url = "https://erddap.incois.gov.in/erddap/griddap/incois_tmi_3day_datasets.nc?SST"

r = requests.get(test_url, verify=False, stream=True, timeout=30)

print("HTTP status:", r.status_code)
print("Content-Type:", r.headers.get("Content-Type"))

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'erddap.incois.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

HTTP status: 413
Content-Type: text/plain;charset=UTF-8

In [57]:
import requests
import os

sst_path = "/content/drive/MyDrive/DATASETS/incois_tmi_sst_2005_2014_indian_ocean.nc"

sst_url = (
    "https://erddap.incois.gov.in/erddap/griddap/"
    "incois_tmi_3day_datasets.nc?"
    "SST"
    "[(2005-01-01T00:00:00Z):10:(2014-12-31T00:00:00Z)]"
    "[(2.5):10:(22.25)]"
    "[(65.5):10:(97.25)]"
)

print("Requesting reduced SST dataset...")

response = requests.get(
    sst_url,
    stream=True,
    verify=False,
    timeout=120
)

print("HTTP status:", response.status_code)

if response.status_code != 200:
    print("\nServer response:")
    print(response.text[:2000])
else:
    total = 0

    with open(sst_path, "wb") as f:
        for chunk in response.iter_content(chunk_size=1024 * 1024):
            if chunk:
                f.write(chunk)
                total += len(chunk)

    print("\n✅ Download complete")
    print(
        "Size (MB):",
        round(total / (1024**2), 2)
    )

Requesting reduced SST dataset...

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'erddap.incois.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

HTTP status: 200

✅ Download complete
Size (MB): 0.15

In [58]:
import xarray as xr

sst_path = "/content/drive/MyDrive/DATASETS/incois_tmi_sst_2005_2014_indian_ocean.nc"

sst = xr.open_dataset(sst_path)

print(sst)

<xarray.Dataset> Size: 155kB
Dimensions:    (time: 365, latitude: 8, longitude: 13)
Coordinates:
  * time       (time) datetime64[ns] 3kB 2005-01-01 2005-01-11 ... 2014-12-22
  * latitude   (latitude) float64 64B 2.5 5.0 7.5 10.0 12.5 15.0 17.5 20.0
  * longitude  (longitude) float64 104B 65.5 68.0 70.5 73.0 ... 90.5 93.0 95.5
Data variables:
    SST        (time, latitude, longitude) float32 152kB ...
Attributes: (12/26)
    cdm_data_type:              Grid
    Conventions:                CF-1.6, COARDS, ACDD-1.3
    Easternmost_Easting:        95.5
    geospatial_lat_max:         20.0
    geospatial_lat_min:         2.5
    geospatial_lat_resolution:  0.25
    ...                         ...
    standard_name_vocabulary:   CF Standard Name Table v29
    summary:                    INCOIS TMI 3Day Data
    time_coverage_end:          2014-12-22T00:00:00Z
    time_coverage_start:        2005-01-01T00:00:00Z
    title:                      INCOIS TMI 3Day Data
    Westernmost_Easting:        65.5

In [59]:
print("Dimensions:")
print(sst.dims)

print("\nVariables:")
print(list(sst.data_vars))

print("\nSST shape:")
print(sst["SST"].shape)

Dimensions:
FrozenMappingWarningOnValuesAccess({'time': 365, 'latitude': 8, 'longitude': 13})

Variables:
['SST']

SST shape:
(365, 8, 13)

In [60]:
import os

if os.path.exists(sst_path):
    os.remove(sst_path)

print("Coarse SST file removed:", not os.path.exists(sst_path))

Coarse SST file removed: True

In [61]:
import requests
import os

sst_path = "/content/drive/MyDrive/DATASETS/incois_tmi_sst_2005_2014_indian_ocean.nc"

sst_url = (
    "https://erddap.incois.gov.in/erddap/griddap/"
    "incois_tmi_3day_datasets.nc?"
    "SST"
    "[(2005-01-01T00:00:00Z):10:(2014-12-31T00:00:00Z)]"
    "[(2.5):1:(20.0)]"
    "[(65.5):1:(95.5)]"
)

print("Requesting SST dataset...")
print("Time: 2005–2014")
print("Latitude: 2.5–20.0°N")
print("Longitude: 65.5–95.5°E")
print("Spatial resolution: 0.25°")

response = requests.get(
    sst_url,
    stream=True,
    verify=False,
    timeout=180
)

print("\nHTTP status:", response.status_code)

if response.status_code != 200:
    print("\n❌ Server error:")
    print(response.text[:2000])

else:
    total = 0

    with open(sst_path, "wb") as f:
        for chunk in response.iter_content(chunk_size=1024 * 1024):
            if chunk:
                f.write(chunk)
                total += len(chunk)

    print("\n✅ Download complete!")
    print(
        "File size (MB):",
        round(total / (1024**2), 2)
    )
    print("File exists:", os.path.exists(sst_path))

Requesting SST dataset...
Time: 2005–2014
Latitude: 2.5–20.0°N
Longitude: 65.5–95.5°E
Spatial resolution: 0.25°

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'erddap.incois.gov.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

HTTP status: 200

✅ Download complete!
File size (MB): 11.97
File exists: True

In [62]:
import xarray as xr

sst = xr.open_dataset(sst_path)

print("Dimensions:")
print(sst.dims)

print("\nVariables:")
print(list(sst.data_vars))

print("\nSST shape:")
print(sst["SST"].shape)

print("\nLatitude range:")
print(float(sst.latitude.min()), "to", float(sst.latitude.max()))

print("\nLongitude range:")
print(float(sst.longitude.min()), "to", float(sst.longitude.max()))

print("\nTime range:")
print(sst.time.values[0], "to", sst.time.values[-1])

Dimensions:
FrozenMappingWarningOnValuesAccess({'time': 365, 'latitude': 71, 'longitude': 121})

Variables:
['SST']

SST shape:
(365, 71, 121)

Latitude range:
2.5 to 20.0

Longitude range:
65.5 to 95.5

Time range:
2005-01-01T00:00:00.000000000 to 2014-12-22T00:00:00.000000000

In [63]:
# Check which historical fishing observations fall inside SST coverage

lat_min = float(sst.latitude.min())
lat_max = float(sst.latitude.max())
lon_min = float(sst.longitude.min())
lon_max = float(sst.longitude.max())

inside = training_fish[
    training_fish["CENTER_LAT"].between(lat_min, lat_max) &
    training_fish["CENTER_LON"].between(lon_min, lon_max)
].copy()

outside = training_fish[
    ~(
        training_fish["CENTER_LAT"].between(lat_min, lat_max) &
        training_fish["CENTER_LON"].between(lon_min, lon_max)
    )
].copy()

print("Total training observations:", len(training_fish))
print("Inside SST coverage:", len(inside))
print("Outside SST coverage:", len(outside))

print("\nUnique fishing grounds inside:", inside["FISHING_GROUND_CODE"].nunique())
print("Unique fishing grounds outside:", outside["FISHING_GROUND_CODE"].nunique())

print("\nOutside observations:")
print(
    outside[
        ["YEAR", "MONTH_START", "FISHING_GROUND_CODE",
         "CENTER_LAT", "CENTER_LON"]
    ].to_string(index=False)
)

Total training observations: 419
Inside SST coverage: 390
Outside SST coverage: 29

Unique fishing grounds inside: 39
Unique fishing grounds outside: 6

Outside observations:
 YEAR  MONTH_START FISHING_GROUND_CODE  CENTER_LAT  CENTER_LON
 2005            4             5120066   20.500000   66.500000
 2005            8             5120066   20.500000   66.500000
 2006            4             5120066   20.500000   66.500000
 2006            9             5120066   20.500000   66.500000
 2007            4             6105095    7.354802   97.193396
 2007            4             6120065   22.126164   67.110223
 2007            5             6120065   22.126164   67.110223
 2007            8             6110095   12.412717   96.701606
 2007            9             6105095    7.354802   97.193396
 2007           10             6120065   22.126164   67.110223
 2007           11             6120065   22.126164   67.110223
 2008            3             6120065   22.126164   67.110223
 2008            4             6120065   22.126164   67.110223
 2008            7             6110095   12.412717   96.701606
 2009            1             6105095    7.354802   97.193396
 2009            1             6110095   12.412717   96.701606
 2009            1             6120065   22.126164   67.110223
 2010            4             6120065   22.126164   67.110223
 2010           11             6110095   12.412717   96.701606
 2010           12             6110095   12.412717   96.701606
 2011            1             6120065   22.126164   67.110223
 2011           10             6115095   15.750573   96.538105
 2012            2             5120065   20.500000   65.500000
 2012            3             5120065   20.500000   65.500000
 2012           11             5120065   20.500000   65.500000
 2013            4             5120065   20.500000   65.500000
 2013            9             5120065   20.500000   65.500000
 2014            4             5120065   20.500000   65.500000
 2014            6             5120065   20.500000   65.500000

In [64]:
import pandas as pd
import numpy as np

# Convert SST time coordinate to pandas datetime
sst_times = pd.to_datetime(sst.time.values)

print("Number of SST time points:", len(sst_times))
print("First 10 SST dates:")
print(sst_times[:10])

print("\nMonths represented:")
print(sorted(sst_times.month.unique()))

Number of SST time points: 365
First 10 SST dates:
DatetimeIndex(['2005-01-01', '2005-01-11', '2005-01-21', '2005-01-31',
               '2005-02-10', '2005-02-20', '2005-03-02', '2005-03-12',
               '2005-03-22', '2005-04-01'],
              dtype='datetime64[ns]', freq=None)

Months represented:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [65]:
# Keep only fishing observations inside SST coverage
fish_sst = training_fish[
    training_fish["CENTER_LAT"].between(
        float(sst.latitude.min()),
        float(sst.latitude.max())
    ) &
    training_fish["CENTER_LON"].between(
        float(sst.longitude.min()),
        float(sst.longitude.max())
    )
].copy()

print("Fishing observations to match:", len(fish_sst))


# Function to get nearest SST for a fishing observation
def get_nearest_sst(row):
    year = int(row["YEAR"])
    month = int(row["MONTH_START"])

    # SST dates belonging to same year and month
    matching_times = sst_times[
        (sst_times.year == year) &
        (sst_times.month == month)
    ]

    if len(matching_times) == 0:
        return np.nan

    # Pick SST date closest to the beginning of the fishing month
    target_date = pd.Timestamp(year=year, month=month, day=1)

    nearest_time = matching_times[
        np.argmin(np.abs(matching_times - target_date))
    ]

    # Extract nearest spatial grid cell
    value = sst["SST"].sel(
        time=nearest_time,
        latitude=row["CENTER_LAT"],
        longitude=row["CENTER_LON"],
        method="nearest"
    ).values

    return float(value)


# Apply to every fishing observation
fish_sst["SST"] = fish_sst.apply(get_nearest_sst, axis=1)

print("\nSST matching complete.")

print("\nMissing SST values:")
print(fish_sst["SST"].isna().sum())

print("\nDataset shape:")
print(fish_sst.shape)

print("\nSample:")
print(
    fish_sst[
        [
            "YEAR",
            "MONTH_START",
            "FISHING_GROUND_CODE",
            "CENTER_LAT",
            "CENTER_LON",
            "CPUE",
            "SST"
        ]
    ].head(10)
)

Fishing observations to match: 390

SST matching complete.

Missing SST values:
100

Dataset shape:
(390, 18)

Sample:
     YEAR  MONTH_START FISHING_GROUND_CODE  CENTER_LAT  CENTER_LON  \
469  2005            1             5110090   10.500000   90.500000
470  2005            1             5114067   14.500000   67.500000
471  2005            2             5114067   14.500000   67.500000
472  2005            2             5115080   15.379402   80.572531
473  2005            2             5115085   15.500000   85.500000
474  2005            2             5119067   19.500000   67.500000
475  2005            3             5114067   14.500000   67.500000
476  2005            3             5119067   19.500000   67.500000
477  2005            4             5105088    5.500000   88.500000
478  2005            4             5110080   10.500000   80.500000

             CPUE        SST
469  4.722286e-04  28.049999
470  6.000000e-06  27.750000
471  1.232000e-05  27.450001
472  7.160000e-05        NaN
473  4.213333e-05  27.150000
474  3.250000e-05  25.350000
475  1.540000e-04  27.450001
476  1.675000e-04  26.100000
477  7.812500e-07  30.000000
478  2.784810e-05  30.299999

In [66]:
# Diagnose why SST values are missing

missing_sst = fish_sst[fish_sst["SST"].isna()].copy()

print("Total missing SST:", len(missing_sst))

print("\nMissing SST by year:")
print(missing_sst["YEAR"].value_counts().sort_index())

print("\nMissing SST by month:")
print(missing_sst["MONTH_START"].value_counts().sort_index())

print("\nMissing SST locations:")
print(
    missing_sst[
        [
            "YEAR",
            "MONTH_START",
            "FISHING_GROUND_CODE",
            "CENTER_LAT",
            "CENTER_LON"
        ]
    ].head(30).to_string(index=False)
)

Total missing SST: 100

Missing SST by year:
YEAR
2005     7
2006     7
2007     5
2008     5
2009     5
2010    13
2011     8
2012     7
2013    38
2014     5
Name: count, dtype: int64

Missing SST by month:
MONTH_START
1     14
2     10
3      9
4     12
5      7
6      4
7      4
8      4
9      9
10    14
11     6
12     7
Name: count, dtype: int64

Missing SST locations:
 YEAR  MONTH_START FISHING_GROUND_CODE  CENTER_LAT  CENTER_LON
 2005            2             5115080   15.379402   80.572531
 2005            6             5115080   15.379402   80.572531
 2005            8             5115080   15.379402   80.572531
 2005           10             5105093    5.500000   93.500000
 2005           10             5115080   15.379402   80.572531
 2005           11             5110080   10.500000   80.500000
 2005           12             5115080   15.379402   80.572531
 2006            1             5115080   15.379402   80.572531
 2006            3             5115080   15.379402   80.572531
 2006            4             5115080   15.379402   80.572531
 2006            9             5115080   15.379402   80.572531
 2006           10             5115080   15.379402   80.572531
 2006           11             5110071   10.500000   71.500000
 2006           12             5115080   15.379402   80.572531
 2007            3             6110090   12.504149   92.494324
 2007            5             6110090   12.504149   92.494324
 2007            8             6110090   12.504149   92.494324
 2007           10             6110090   12.504149   92.494324
 2007           11             6110090   12.504149   92.494324
 2008            1             6110090   12.504149   92.494324
 2008            2             6110090   12.504149   92.494324
 2008            7             6110090   12.504149   92.494324
 2008           10             6110090   12.504149   92.494324
 2008           12             6110090   12.504149   92.494324
 2009            1             6110090   12.504149   92.494324
 2009           10             6110090   12.504149   92.494324
 2009           11             6110080   12.476727   82.554531
 2009           11             6110090   12.504149   92.494324
 2009           12             6110090   12.504149   92.494324
 2010            1             6110090   12.504149   92.494324

In [67]:
# Check whether the SST dataset itself contains NaNs

total_sst_values = sst["SST"].size
missing_sst_values = int(sst["SST"].isnull().sum())

print("Total SST grid values:", total_sst_values)
print("Missing SST grid values:", missing_sst_values)

print(
    "Percentage of SST grid missing:",
    round(100 * missing_sst_values / total_sst_values, 2),
    "%"
)

Total SST grid values: 3135715
Missing SST grid values: 1098582
Percentage of SST grid missing: 35.03 %

In [68]:
missing_sst = fish_sst[fish_sst["SST"].isna()].copy()

print("Total missing SST:", len(missing_sst))

print("\nMissing SST by year:")
print(missing_sst["YEAR"].value_counts().sort_index())

print("\nMissing SST by month:")
print(missing_sst["MONTH_START"].value_counts().sort_index())

print("\nMissing SST locations:")
print(
    missing_sst[
        [
            "YEAR",
            "MONTH_START",
            "FISHING_GROUND_CODE",
            "CENTER_LAT",
            "CENTER_LON"
        ]
    ].head(30).to_string(index=False)
)

Total missing SST: 100

Missing SST by year:
YEAR
2005     7
2006     7
2007     5
2008     5
2009     5
2010    13
2011     8
2012     7
2013    38
2014     5
Name: count, dtype: int64

Missing SST by month:
MONTH_START
1     14
2     10
3      9
4     12
5      7
6      4
7      4
8      4
9      9
10    14
11     6
12     7
Name: count, dtype: int64

Missing SST locations:
 YEAR  MONTH_START FISHING_GROUND_CODE  CENTER_LAT  CENTER_LON
 2005            2             5115080   15.379402   80.572531
 2005            6             5115080   15.379402   80.572531
 2005            8             5115080   15.379402   80.572531
 2005           10             5105093    5.500000   93.500000
 2005           10             5115080   15.379402   80.572531
 2005           11             5110080   10.500000   80.500000
 2005           12             5115080   15.379402   80.572531
 2006            1             5115080   15.379402   80.572531
 2006            3             5115080   15.379402   80.572531
 2006            4             5115080   15.379402   80.572531
 2006            9             5115080   15.379402   80.572531
 2006           10             5115080   15.379402   80.572531
 2006           11             5110071   10.500000   71.500000
 2006           12             5115080   15.379402   80.572531
 2007            3             6110090   12.504149   92.494324
 2007            5             6110090   12.504149   92.494324
 2007            8             6110090   12.504149   92.494324
 2007           10             6110090   12.504149   92.494324
 2007           11             6110090   12.504149   92.494324
 2008            1             6110090   12.504149   92.494324
 2008            2             6110090   12.504149   92.494324
 2008            7             6110090   12.504149   92.494324
 2008           10             6110090   12.504149   92.494324
 2008           12             6110090   12.504149   92.494324
 2009            1             6110090   12.504149   92.494324
 2009           10             6110090   12.504149   92.494324
 2009           11             6110080   12.476727   82.554531
 2009           11             6110090   12.504149   92.494324
 2009           12             6110090   12.504149   92.494324
 2010            1             6110090   12.504149   92.494324

In [69]:
# Check whether nearby SST cells can recover the missing observations

def nearby_sst_check(row, radius=1):
    year = int(row["YEAR"])
    month = int(row["MONTH_START"])

    matching_times = sst_times[
        (sst_times.year == year) &
        (sst_times.month == month)
    ]

    if len(matching_times) == 0:
        return np.nan

    target_date = pd.Timestamp(year=year, month=month, day=1)

    nearest_time = matching_times[
        np.argmin(np.abs(matching_times - target_date))
    ]

    # Find nearest grid indices
    lat_idx = int(
        np.abs(sst.latitude.values - row["CENTER_LAT"]).argmin()
    )
    lon_idx = int(
        np.abs(sst.longitude.values - row["CENTER_LON"]).argmin()
    )

    lat_start = max(0, lat_idx - radius)
    lat_end = min(len(sst.latitude), lat_idx + radius + 1)

    lon_start = max(0, lon_idx - radius)
    lon_end = min(len(sst.longitude), lon_idx + radius + 1)

    neighborhood = sst["SST"].sel(
        time=nearest_time
    ).isel(
        latitude=slice(lat_start, lat_end),
        longitude=slice(lon_start, lon_end)
    ).values

    valid = neighborhood[~np.isnan(neighborhood)]

    return len(valid)


missing_sst["NEARBY_VALID_CELLS"] = missing_sst.apply(
    nearby_sst_check,
    axis=1
)

print("Missing observations:", len(missing_sst))

print("\nNearby valid cells within 1 grid cell:")
print(
    missing_sst["NEARBY_VALID_CELLS"]
    .value_counts()
    .sort_index()
)

print(
    "\nRecoverable using immediate 3x3 neighborhood:",
    (missing_sst["NEARBY_VALID_CELLS"] > 0).sum()
)

Missing observations: 100

Nearby valid cells within 1 grid cell:
NEARBY_VALID_CELLS
0    96
3     2
5     2
Name: count, dtype: int64

Recoverable using immediate 3x3 neighborhood: 4

In [70]:
# Check whether missing SST cells have a valid SST
# on another date within the SAME month.

def count_valid_sst_in_month(row):
    year = int(row["YEAR"])
    month = int(row["MONTH_START"])

    matching_times = sst_times[
        (sst_times.year == year) &
        (sst_times.month == month)
    ]

    if len(matching_times) == 0:
        return 0

    # Find nearest spatial grid cell
    lat_idx = int(
        np.abs(sst.latitude.values - row["CENTER_LAT"]).argmin()
    )

    lon_idx = int(
        np.abs(sst.longitude.values - row["CENTER_LON"]).argmin()
    )

    values = sst["SST"].isel(
        time=[
            sst_times.get_loc(t)
            for t in matching_times
        ],
        latitude=lat_idx,
        longitude=lon_idx
    ).values

    return int(np.sum(~np.isnan(values)))


missing_sst["VALID_DATES_IN_MONTH"] = missing_sst.apply(
    count_valid_sst_in_month,
    axis=1
)

print("Missing observations:", len(missing_sst))

print("\nValid SST dates available within the same month:")
print(
    missing_sst["VALID_DATES_IN_MONTH"]
    .value_counts()
    .sort_index()
)

print(
    "\nPotentially recoverable:",
    (missing_sst["VALID_DATES_IN_MONTH"] > 0).sum()
)

Missing observations: 100

Valid SST dates available within the same month:
VALID_DATES_IN_MONTH
0    95
1     1
2     4
Name: count, dtype: int64

Potentially recoverable: 5

In [71]:
# Keep only observations with valid SST
fish_sst_valid = fish_sst.dropna(subset=["SST"]).copy()

print("Original SST-matched observations:", len(fish_sst))
print("Valid SST observations:", len(fish_sst_valid))
print("Removed due to missing SST:", len(fish_sst) - len(fish_sst_valid))

print("\nUnique fishing grounds:")
print(fish_sst_valid["FISHING_GROUND_CODE"].nunique())

print("\nYears:")
print(
    fish_sst_valid["YEAR"]
    .value_counts()
    .sort_index()
)

print("\nSST statistics:")
print(fish_sst_valid["SST"].describe())

Original SST-matched observations: 390
Valid SST observations: 290
Removed due to missing SST: 100

Unique fishing grounds:
34

Years:
YEAR
2005    41
2006    33
2007    34
2008    32
2009    32
2010    28
2011    46
2012    29
2014    15
Name: count, dtype: int64

SST statistics:
count    290.000000
mean      28.709483
std        1.176127
min       25.350000
25%       28.049999
50%       28.724999
75%       29.549999
max       31.950001
Name: SST, dtype: float64

In [72]:
print(fish_sst_valid.columns.tolist())

['YEAR', 'MONTH_START', 'MONTH_END', 'FISHING_GROUND_CODE', 'FLEET_CODE', 'FISHERY_TYPE_CODE', 'FISHERY_GROUP_CODE', 'FISHERY_CODE', 'GEAR_CODE', 'TOTAL_CATCH_MT', 'GEAR', 'EFFORT_UNIT_CODE', 'EFFORT', 'CPUE', 'CODE', 'CENTER_LAT', 'CENTER_LON', 'SST']

In [73]:
print("Gear distribution:")
print(
    fish_sst_valid["GEAR"]
    .value_counts()
)

print("\nEffort unit distribution:")
print(
    fish_sst_valid["EFFORT_UNIT_CODE"]
    .value_counts()
)

print("\nCPUE by effort unit:")
print(
    fish_sst_valid.groupby("EFFORT_UNIT_CODE")["CPUE"]
    .agg(["count", "mean", "median", "min", "max"])
)

Gear distribution:
GEAR
Longline (exploratory)      225
Longline (deep-freezing)     65
Name: count, dtype: int64

Effort unit distribution:
EFFORT_UNIT_CODE
HOOKS    290
Name: count, dtype: int64

CPUE by effort unit:
                  count      mean    median           min       max
EFFORT_UNIT_CODE
HOOKS               290  0.000105  0.000041  3.174603e-07  0.006667

In [74]:
import numpy as np

print("CPUE percentiles:")
print(
    fish_sst_valid["CPUE"].quantile(
        [0, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 1.0]
    )
)

print("\nCPUE > 10x median:")
median_cpue = fish_sst_valid["CPUE"].median()

print(
    (fish_sst_valid["CPUE"] > 10 * median_cpue).sum(),
    "observations"
)

print("\nCPUE > 100x median:")
print(
    (fish_sst_valid["CPUE"] > 100 * median_cpue).sum(),
    "observations"
)

CPUE percentiles:
0.00    3.174603e-07
0.25    1.732869e-05
0.50    4.125031e-05
0.75    9.431700e-05
0.90    2.177516e-04
0.95    2.921140e-04
0.99    5.551319e-04
1.00    6.666667e-03
Name: CPUE, dtype: float64

CPUE > 10x median:
10 observations

CPUE > 100x median:
1 observations

In [75]:
# Create log-transformed CPUE target

fish_sst_valid = fish_sst_valid.copy()

fish_sst_valid["LOG_CPUE"] = np.log1p(
    fish_sst_valid["CPUE"]
)

print("Original CPUE:")
print(fish_sst_valid["CPUE"].describe())

print("\nLog-transformed CPUE:")
print(fish_sst_valid["LOG_CPUE"].describe())

print("\nMissing LOG_CPUE:")
print(fish_sst_valid["LOG_CPUE"].isna().sum())

Original CPUE:
count    2.900000e+02
mean     1.050939e-04
std      4.068042e-04
min      3.174603e-07
25%      1.732869e-05
50%      4.125031e-05
75%      9.431700e-05
max      6.666667e-03
Name: CPUE, dtype: float64

Log-transformed CPUE:
count    2.900000e+02
mean     1.050062e-04
std      4.055551e-04
min      3.174603e-07
25%      1.732854e-05
50%      4.124945e-05
75%      9.431256e-05
max      6.644543e-03
Name: LOG_CPUE, dtype: float64

Missing LOG_CPUE:
0

In [76]:
# Use natural logarithm of CPUE as the regression target

fish_sst_valid["LOG_CPUE"] = np.log(
    fish_sst_valid["CPUE"]
)

print("Log(CPUE) statistics:")
print(
    fish_sst_valid["LOG_CPUE"].describe()
)

print("\nMissing values:")
print(
    fish_sst_valid["LOG_CPUE"].isna().sum()
)

Log(CPUE) statistics:
count    290.000000
mean     -10.198278
std        1.452811
min      -14.962913
25%      -10.963317
50%      -10.095852
75%       -9.268852
max       -5.010635
Name: LOG_CPUE, dtype: float64

Missing values:
0

In [77]:
# ==============================
# FEATURE ENGINEERING
# ==============================

model_df = fish_sst_valid.copy()

# Month as a circular/seasonal feature
model_df["MONTH_SIN"] = np.sin(
    2 * np.pi * model_df["MONTH_START"] / 12
)

model_df["MONTH_COS"] = np.cos(
    2 * np.pi * model_df["MONTH_START"] / 12
)

# Features we will give to the model
feature_columns = [
    "SST",
    "CENTER_LAT",
    "CENTER_LON",
    "MONTH_SIN",
    "MONTH_COS",
    "GEAR"
]

target_column = "LOG_CPUE"

print("Features:")
print(feature_columns)

print("\nTarget:")
print(target_column)

print("\nModel dataset shape:")
print(model_df[feature_columns + [target_column]].shape)

print("\nMissing values:")
print(
    model_df[feature_columns + [target_column]]
    .isna()
    .sum()
)

print("\nSample:")
print(
    model_df[
        feature_columns + [target_column]
    ].head()
)

Features:
['SST', 'CENTER_LAT', 'CENTER_LON', 'MONTH_SIN', 'MONTH_COS', 'GEAR']

Target:
LOG_CPUE

Model dataset shape:
(290, 7)

Missing values:
SST           0
CENTER_LAT    0
CENTER_LON    0
MONTH_SIN     0
MONTH_COS     0
GEAR          0
LOG_CPUE      0
dtype: int64

Sample:
           SST  CENTER_LAT  CENTER_LON  MONTH_SIN  MONTH_COS  \
469  28.049999        10.5        90.5   0.500000   0.866025
470  27.750000        14.5        67.5   0.500000   0.866025
471  27.450001        14.5        67.5   0.866025   0.500000
473  27.150000        15.5        85.5   0.866025   0.500000
474  25.350000        19.5        67.5   0.866025   0.500000

                       GEAR   LOG_CPUE
469  Longline (exploratory)  -7.658047
470  Longline (exploratory) -12.023751
471  Longline (exploratory) -11.304287
473  Longline (exploratory) -10.074671
474  Longline (exploratory) -10.334270

In [78]:
# ==========================================
# TIME-BASED TRAIN / TEST SPLIT
# ==========================================

train_df = model_df[
    model_df["YEAR"] <= 2011
].copy()

test_df = model_df[
    model_df["YEAR"] >= 2012
].copy()

print("Training years:",
      train_df["YEAR"].min(),
      "to",
      train_df["YEAR"].max())

print("Testing years:",
      test_df["YEAR"].min(),
      "to",
      test_df["YEAR"].max())

print("\nTraining observations:", len(train_df))
print("Testing observations:", len(test_df))

print("\nTraining observations by year:")
print(train_df["YEAR"].value_counts().sort_index())

print("\nTesting observations by year:")
print(test_df["YEAR"].value_counts().sort_index())

Training years: 2005 to 2011
Testing years: 2012 to 2014

Training observations: 246
Testing observations: 44

Training observations by year:
YEAR
2005    41
2006    33
2007    34
2008    32
2009    32
2010    28
2011    46
Name: count, dtype: int64

Testing observations by year:
YEAR
2012    29
2014    15
Name: count, dtype: int64

In [79]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Features
X_train = train_df[feature_columns]
y_train = train_df[target_column]

X_test = test_df[feature_columns]
y_test = test_df[target_column]

# Categorical + numerical features
categorical_features = ["GEAR"]
numeric_features = [
    "SST",
    "CENTER_LAT",
    "CENTER_LON",
    "MONTH_SIN",
    "MONTH_COS"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numeric_features
        )
    ]
)

# Random Forest
rf_model = RandomForestRegressor(
    n_estimators=300,
    max_depth=8,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)

# Complete pipeline
model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", rf_model)
    ]
)

# Train
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MODEL PERFORMANCE")
print("-----------------")
print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

MODEL PERFORMANCE
-----------------
MAE : 1.1525407158961318
RMSE: 1.4706998213900755
R²  : 0.33375520856787755

In [80]:
# ==========================================
# BASELINE MODEL
# ==========================================

# Predict the training mean for every test observation
baseline_pred = np.full(
    len(y_test),
    y_train.mean()
)

baseline_mae = mean_absolute_error(
    y_test,
    baseline_pred
)

baseline_rmse = np.sqrt(
    mean_squared_error(y_test, baseline_pred)
)

baseline_r2 = r2_score(
    y_test,
    baseline_pred
)

print("BASELINE PERFORMANCE")
print("--------------------")
print("MAE :", baseline_mae)
print("RMSE:", baseline_rmse)
print("R²  :", baseline_r2)

print("\nRANDOM FOREST")
print("--------------------")
print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

print("\nImprovement in MAE:")
print(
    round(
        100 * (baseline_mae - mae) / baseline_mae,
        2
    ),
    "%"
)

print("\nImprovement in RMSE:")
print(
    round(
        100 * (baseline_rmse - rmse) / baseline_rmse,
        2
    ),
    "%"
)

BASELINE PERFORMANCE
--------------------
MAE : 1.4903788351766585
RMSE: 1.8030664661123068
R²  : -0.001403765568765536

RANDOM FOREST
--------------------
MAE : 1.1525407158961318
RMSE: 1.4706998213900755
R²  : 0.33375520856787755

Improvement in MAE:
22.67 %

Improvement in RMSE:
18.43 %

In [81]:
# ==========================================
# FEATURE IMPORTANCE
# ==========================================

# Get transformed feature names
feature_names = (
    model.named_steps["preprocessor"]
    .get_feature_names_out()
)

# Get Random Forest importance
importances = (
    model.named_steps["model"]
    .feature_importances_
)

importance_df = pd.DataFrame({
    "FEATURE": feature_names,
    "IMPORTANCE": importances
}).sort_values(
    "IMPORTANCE",
    ascending=False
)

print("FEATURE IMPORTANCE")
print("==================")

print(
    importance_df.to_string(index=False)
)

FEATURE IMPORTANCE
==================
                           FEATURE  IMPORTANCE
                    num__MONTH_COS    0.200149
                   num__CENTER_LON    0.196869
                          num__SST    0.155941
                    num__MONTH_SIN    0.130460
                   num__CENTER_LAT    0.127124
  cat__GEAR_Longline (exploratory)    0.096809
cat__GEAR_Longline (deep-freezing)    0.092647

In [82]:
from sklearn.inspection import permutation_importance

# Permutation importance on the FUTURE test set
perm = permutation_importance(
    model,
    X_test,
    y_test,
    scoring="r2",
    n_repeats=20,
    random_state=42,
    n_jobs=-1
)

perm_df = pd.DataFrame({
    "FEATURE": X_test.columns,
    "IMPORTANCE_MEAN": perm.importances_mean,
    "IMPORTANCE_STD": perm.importances_std
}).sort_values(
    "IMPORTANCE_MEAN",
    ascending=False
)

print("PERMUTATION IMPORTANCE — TEST SET")
print("=================================")

print(
    perm_df.to_string(index=False)
)

PERMUTATION IMPORTANCE — TEST SET
=================================
   FEATURE  IMPORTANCE_MEAN  IMPORTANCE_STD
      GEAR         0.354899        0.122098
 MONTH_SIN         0.045919        0.023066
 MONTH_COS         0.039882        0.037566
CENTER_LAT         0.008009        0.027528
CENTER_LON         0.007193        0.021682
       SST        -0.014767        0.016947

In [83]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


def train_and_evaluate(features, name):

    categorical = ["GEAR"] if "GEAR" in features else []

    numerical = [
        f for f in features
        if f != "GEAR"
    ]

    preprocessor = ColumnTransformer(
        transformers=[
            (
                "cat",
                OneHotEncoder(handle_unknown="ignore"),
                categorical
            ),
            (
                "num",
                "passthrough",
                numerical
            )
        ]
    )

    rf = RandomForestRegressor(
        n_estimators=300,
        max_depth=8,
        min_samples_leaf=5,
        random_state=42,
        n_jobs=-1
    )

    pipeline = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("model", rf)
        ]
    )

    pipeline.fit(
        train_df[features],
        train_df["LOG_CPUE"]
    )

    predictions = pipeline.predict(
        test_df[features]
    )

    return {
        "Model": name,
        "MAE": mean_absolute_error(
            test_df["LOG_CPUE"],
            predictions
        ),
        "RMSE": np.sqrt(
            mean_squared_error(
                test_df["LOG_CPUE"],
                predictions
            )
        ),
        "R2": r2_score(
            test_df["LOG_CPUE"],
            predictions
        )
    }


# ------------------------------------------
# MODEL A: GEAR ONLY
# ------------------------------------------

model_a = train_and_evaluate(
    ["GEAR"],
    "A: Gear only"
)


# ------------------------------------------
# MODEL B: GEAR + SEASON
# ------------------------------------------

model_b = train_and_evaluate(
    [
        "GEAR",
        "MONTH_SIN",
        "MONTH_COS"
    ],
    "B: Gear + Season"
)


# ------------------------------------------
# MODEL C: ALL FEATURES
# ------------------------------------------

model_c = train_and_evaluate(
    [
        "GEAR",
        "MONTH_SIN",
        "MONTH_COS",
        "CENTER_LAT",
        "CENTER_LON",
        "SST"
    ],
    "C: Gear + Season + Location + SST"
)


# ------------------------------------------
# RESULTS
# ------------------------------------------

ablation_results = pd.DataFrame([
    model_a,
    model_b,
    model_c
])

print(
    ablation_results.to_string(index=False)
)

                            Model      MAE     RMSE       R2
                     A: Gear only 1.130854 1.499015 0.307854
                 B: Gear + Season 1.168284 1.519008 0.289268
C: Gear + Season + Location + SST 1.153075 1.470988 0.333494

In [84]:
# ==========================================
# LOCATION / ENVIRONMENT MODEL
# ==========================================

features_no_gear = [
    "MONTH_SIN",
    "MONTH_COS",
    "CENTER_LAT",
    "CENTER_LON",
    "SST"
]

model_no_gear = train_and_evaluate(
    features_no_gear,
    "No Gear: Season + Location + SST"
)

print(
    pd.DataFrame([model_no_gear]).to_string(index=False)
)

                           Model      MAE     RMSE       R2
No Gear: Season + Location + SST 1.371414 1.660224 0.150978

In [85]:
# ==========================================
# ACTUAL VS PREDICTED
# ==========================================

results = test_df[
    [
        "YEAR",
        "MONTH_START",
        "FISHING_GROUND_CODE",
        "CENTER_LAT",
        "CENTER_LON",
        "CPUE",
        "LOG_CPUE"
    ]
].copy()

results["PRED_LOG_CPUE"] = y_pred

# Convert predictions back to CPUE
results["PRED_CPUE"] = np.exp(
    results["PRED_LOG_CPUE"]
)

# Absolute error
results["ABS_ERROR"] = np.abs(
    results["CPUE"] - results["PRED_CPUE"]
)

# Rank actual and predicted productivity
results["ACTUAL_RANK"] = results["CPUE"].rank(
    ascending=False,
    method="min"
)

results["PREDICTED_RANK"] = results["PRED_CPUE"].rank(
    ascending=False,
    method="min"
)

results = results.sort_values(
    "PRED_CPUE",
    ascending=False
)

print("TOP PREDICTED OBSERVATIONS")
print("==========================")

print(
    results[
        [
            "YEAR",
            "MONTH_START",
            "FISHING_GROUND_CODE",
            "CPUE",
            "PRED_CPUE",
            "ACTUAL_RANK",
            "PREDICTED_RANK"
        ]
    ].head(15).to_string(index=False)
)

TOP PREDICTED OBSERVATIONS
==========================
 YEAR  MONTH_START FISHING_GROUND_CODE     CPUE  PRED_CPUE  ACTUAL_RANK  PREDICTED_RANK
 2012            1             5110070 0.000223   0.000325         10.0             1.0
 2012            1             5110080 0.000248   0.000291          8.0             2.0
 2012            1             5115085 0.000319   0.000162          1.0             3.0
 2012            1             5110085 0.000217   0.000155         11.0             4.0
 2012            1             5110090 0.000145   0.000129         17.0             5.0
 2012            2             5115070 0.000254   0.000091          7.0             6.0
 2012            3             5115070 0.000279   0.000091          4.0             7.0
 2012            2             5115065 0.000210   0.000089         12.0             8.0
 2012            2             5110070 0.000282   0.000087          3.0             9.0
 2012            3             5110070 0.000290   0.000085          2.0            10.0
 2012            2             5110085 0.000192   0.000075         13.0            11.0
 2012            1             5105090 0.000170   0.000073         15.0            12.0
 2012            2             5110090 0.000176   0.000069         14.0            13.0
 2012            3             5110090 0.000090   0.000062         19.0            14.0
 2014           12             5110090 0.000026   0.000056         27.0            15.0

In [86]:
from scipy.stats import spearmanr

# Rank correlation between actual and predicted productivity
spearman_corr, spearman_p = spearmanr(
    results["CPUE"],
    results["PRED_CPUE"]
)

print("RANKING EVALUATION")
print("==================")
print("Spearman correlation:", round(spearman_corr, 4))
print("p-value:", round(spearman_p, 4))

RANKING EVALUATION
==================
Spearman correlation: 0.6501
p-value: 0.0

In [87]:
# ==========================================
# TOP-K RANKING ACCURACY
# ==========================================

def top_k_overlap(results, k):
    actual_top = set(
        results.nlargest(k, "CPUE")[
            "FISHING_GROUND_CODE"
        ]
    )

    predicted_top = set(
        results.nlargest(k, "PRED_CPUE")[
            "FISHING_GROUND_CODE"
        ]
    )

    overlap = actual_top.intersection(predicted_top)

    return {
        "K": k,
        "Actual_Top_K": len(actual_top),
        "Predicted_Top_K": len(predicted_top),
        "Correct": len(overlap),
        "Overlap_%": 100 * len(overlap) / k
    }


top5 = top_k_overlap(results, 5)
top10 = top_k_overlap(results, 10)

print("TOP-K RANKING PERFORMANCE")
print("=========================")

print("\nTop-5:")
print(top5)

print("\nTop-10:")
print(top10)

TOP-K RANKING PERFORMANCE
=========================

Top-5:
{'K': 5, 'Actual_Top_K': 4, 'Predicted_Top_K': 5, 'Correct': 2, 'Overlap_%': 40.0}

Top-10:
{'K': 10, 'Actual_Top_K': 5, 'Predicted_Top_K': 7, 'Correct': 5, 'Overlap_%': 50.0}

In [88]:
# ==========================================
# PROPER GROUND-LEVEL TOP-K EVALUATION
# ==========================================

# Each row currently represents a fishing observation.
# We first aggregate observations for the same
# fishing ground + month.

ground_month_results = (
    results
    .groupby(
        ["YEAR", "MONTH_START", "FISHING_GROUND_CODE"],
        as_index=False
    )
    .agg(
        ACTUAL_CPUE=("CPUE", "mean"),
        PRED_CPUE=("PRED_CPUE", "mean"),
        CENTER_LAT=("CENTER_LAT", "first"),
        CENTER_LON=("CENTER_LON", "first")
    )
)

print("Ground-month observations:", len(ground_month_results))
print(
    "Unique fishing grounds:",
    ground_month_results["FISHING_GROUND_CODE"].nunique()
)

print("\nSample:")
print(
    ground_month_results.head(10).to_string(index=False)
)

Ground-month observations: 43
Unique fishing grounds: 8

Sample:
 YEAR  MONTH_START FISHING_GROUND_CODE  ACTUAL_CPUE  PRED_CPUE  CENTER_LAT  CENTER_LON
 2012            1             5105090     0.000170   0.000073         5.5        90.5
 2012            1             5110070     0.000119   0.000177        10.5        70.5
 2012            1             5110080     0.000248   0.000291        10.5        80.5
 2012            1             5110085     0.000217   0.000155        10.5        85.5
 2012            1             5110090     0.000145   0.000129        10.5        90.5
 2012            1             5115085     0.000319   0.000162        15.5        85.5
 2012            2             5105090     0.000170   0.000051         5.5        90.5
 2012            2             5110070     0.000282   0.000087        10.5        70.5
 2012            2             5110085     0.000192   0.000075        10.5        85.5
 2012            2             5110090     0.000176   0.000069        10.5        90.5

In [89]:
# ==========================================
# GROUND-LEVEL TOP-K EVALUATION BY MONTH
# ==========================================

def monthly_top_k_overlap(df, k):
    scores = []

    for (year, month), group in df.groupby(
        ["YEAR", "MONTH_START"]
    ):
        # Skip months with fewer than k grounds
        if len(group) < k:
            continue

        actual_top = set(
            group.nlargest(k, "ACTUAL_CPUE")[
                "FISHING_GROUND_CODE"
            ]
        )

        predicted_top = set(
            group.nlargest(k, "PRED_CPUE")[
                "FISHING_GROUND_CODE"
            ]
        )

        correct = len(
            actual_top.intersection(predicted_top)
        )

        scores.append({
            "YEAR": year,
            "MONTH": month,
            "GROUNDS": len(group),
            "CORRECT": correct,
            "OVERLAP_%": 100 * correct / k
        })

    return pd.DataFrame(scores)


top5_monthly = monthly_top_k_overlap(
    ground_month_results,
    5
)

print("MONTHLY TOP-5 RANKING")
print("=====================")

print(
    top5_monthly.to_string(index=False)
)

print("\nAverage Top-5 overlap:",
      round(top5_monthly["OVERLAP_%"].mean(), 2),
      "%")

MONTHLY TOP-5 RANKING
=====================
 YEAR  MONTH  GROUNDS  CORRECT  OVERLAP_%
 2012      1        6        4       80.0
 2012      2        6        5      100.0
 2012      3        5        5      100.0

Average Top-5 overlap: 93.33 %

In [90]:
# ==========================================
# TOP-10 FISHING GROUND PREDICTOR
# ==========================================

def predict_top_grounds(year, month, gear):

    # Candidate fishing grounds from our historical data
    candidates = fish_geo_valid[
        fish_geo_valid["FISHING_GROUND_CODE"].notna() &
        fish_geo_valid["CENTER_LAT"].notna() &
        fish_geo_valid["CENTER_LON"].notna()
    ][
        [
            "FISHING_GROUND_CODE",
            "CENTER_LAT",
            "CENTER_LON"
        ]
    ].drop_duplicates(
        "FISHING_GROUND_CODE"
    ).copy()

    # Keep only grounds covered by our SST dataset
    candidates = candidates[
        candidates["CENTER_LAT"].between(
            float(sst.latitude.min()),
            float(sst.latitude.max())
        ) &
        candidates["CENTER_LON"].between(
            float(sst.longitude.min()),
            float(sst.longitude.max())
        )
    ].copy()

    # --------------------------------------
    # Find SST date for requested month
    # --------------------------------------

    matching_times = sst_times[
        (sst_times.year == year) &
        (sst_times.month == month)
    ]

    if len(matching_times) == 0:
        raise ValueError(
            f"No SST data available for {year}-{month:02d}"
        )

    target_date = pd.Timestamp(
        year=year,
        month=month,
        day=1
    )

    nearest_time = matching_times[
        np.argmin(
            np.abs(matching_times - target_date)
        )
    ]

    # --------------------------------------
    # Extract SST for each ground
    # --------------------------------------

    def extract_sst(row):

        value = sst["SST"].sel(
            time=nearest_time,
            latitude=row["CENTER_LAT"],
            longitude=row["CENTER_LON"],
            method="nearest"
        ).values

        return float(value)

    candidates["SST"] = candidates.apply(
        extract_sst,
        axis=1
    )

    # Remove grounds where satellite SST is unavailable
    candidates = candidates.dropna(
        subset=["SST"]
    ).copy()

    # --------------------------------------
    # Create seasonal features
    # --------------------------------------

    candidates["MONTH_SIN"] = np.sin(
        2 * np.pi * month / 12
    )

    candidates["MONTH_COS"] = np.cos(
        2 * np.pi * month / 12
    )

    candidates["GEAR"] = gear

    # --------------------------------------
    # Predict productivity
    # --------------------------------------

    candidates["PRED_LOG_CPUE"] = model.predict(
        candidates[feature_columns]
    )

    candidates["PRED_CPUE"] = np.exp(
        candidates["PRED_LOG_CPUE"]
    )

    # --------------------------------------
    # Rank
    # --------------------------------------

    top10 = candidates.sort_values(
        "PRED_CPUE",
        ascending=False
    ).head(10).reset_index(drop=True)

    top10["RANK"] = (
        top10.index + 1
    )

    return top10[
        [
            "RANK",
            "FISHING_GROUND_CODE",
            "CENTER_LAT",
            "CENTER_LON",
            "SST",
            "PRED_CPUE"
        ]
    ]

In [91]:
# Test prediction for January 2012

top10_jan_2012 = predict_top_grounds(
    year=2012,
    month=1,
    gear="Longline (exploratory)"
)

print("TOP 10 PREDICTED FISHING GROUNDS")
print("================================")

print(
    top10_jan_2012.to_string(index=False)
)

TOP 10 PREDICTED FISHING GROUNDS
================================
 RANK FISHING_GROUND_CODE  CENTER_LAT  CENTER_LON       SST  PRED_CPUE
    1             5110088   10.500000   88.500000 27.900000   0.000083
    2             5110090   10.500000   90.500000 28.350000   0.000081
    3             5110093   10.500000   93.500000 28.049999   0.000073
    4             6115090   17.368863   92.184274 27.600000   0.000064
    5             6115080   16.365458   83.268322 27.900000   0.000048
    6             5110085   10.500000   85.500000 27.750000   0.000048
    7             5115085   15.500000   85.500000 27.900000   0.000046
    8             6105090    7.499989   92.493752 29.700001   0.000045
    9             6110085   12.500000   87.500000 27.600000   0.000042
   10             6115085   17.461143   87.534336 26.850000   0.000042

In [92]:
# ==========================================
# COMPARE PREDICTION WITH ACTUAL JAN 2012
# ==========================================

actual_jan = (
    test_df[
        (test_df["YEAR"] == 2012) &
        (test_df["MONTH_START"] == 1)
    ][
        [
            "FISHING_GROUND_CODE",
            "CENTER_LAT",
            "CENTER_LON",
            "CPUE"
        ]
    ]
    .groupby("FISHING_GROUND_CODE", as_index=False)
    .agg(
        ACTUAL_CPUE=("CPUE", "mean"),
        CENTER_LAT=("CENTER_LAT", "first"),
        CENTER_LON=("CENTER_LON", "first")
    )
)

comparison = top10_jan_2012.merge(
    actual_jan,
    on="FISHING_GROUND_CODE",
    how="left",
    suffixes=("_PRED", "_ACTUAL")
)

print("JANUARY 2012 — PREDICTED TOP 10")
print("================================")

print(
    comparison[
        [
            "RANK",
            "FISHING_GROUND_CODE",
            "SST",
            "PRED_CPUE",
            "ACTUAL_CPUE"
        ]
    ].to_string(index=False)
)

print("\nGrounds with actual January 2012 observations:")
print(actual_jan["FISHING_GROUND_CODE"].tolist())

JANUARY 2012 — PREDICTED TOP 10
================================
 RANK FISHING_GROUND_CODE       SST  PRED_CPUE  ACTUAL_CPUE
    1             5110088 27.900000   0.000083          NaN
    2             5110090 28.350000   0.000081     0.000145
    3             5110093 28.049999   0.000073          NaN
    4             6115090 27.600000   0.000064          NaN
    5             6115080 27.900000   0.000048          NaN
    6             5110085 27.750000   0.000048     0.000217
    7             5115085 27.900000   0.000046     0.000319
    8             6105090 29.700001   0.000045          NaN
    9             6110085 27.600000   0.000042          NaN
   10             6115085 26.850000   0.000042          NaN

Grounds with actual January 2012 observations:
['5105090', '5110070', '5110080', '5110085', '5110090', '5115085']

In [93]:
# ==========================================
# FAIR JANUARY 2012 RANKING EVALUATION
# ==========================================

# Keep only predicted grounds that actually
# have an observed January 2012 CPUE
jan_evaluable = comparison.dropna(
    subset=["ACTUAL_CPUE"]
).copy()

# Rank by actual and predicted productivity
jan_evaluable["ACTUAL_RANK"] = (
    jan_evaluable["ACTUAL_CPUE"]
    .rank(ascending=False, method="min")
)

jan_evaluable["PREDICTED_RANK"] = (
    jan_evaluable["PRED_CPUE"]
    .rank(ascending=False, method="min")
)

jan_evaluable = jan_evaluable.sort_values(
    "PREDICTED_RANK"
)

print("JANUARY 2012 — FAIR COMPARISON")
print("================================")

print(
    jan_evaluable[
        [
            "FISHING_GROUND_CODE",
            "ACTUAL_CPUE",
            "PRED_CPUE",
            "ACTUAL_RANK",
            "PREDICTED_RANK"
        ]
    ].to_string(index=False)
)

print(
    "\nGrounds found by model:",
    len(jan_evaluable),
    "out of",
    len(actual_jan)
)

JANUARY 2012 — FAIR COMPARISON
================================
FISHING_GROUND_CODE  ACTUAL_CPUE  PRED_CPUE  ACTUAL_RANK  PREDICTED_RANK
            5110090     0.000145   0.000081          3.0             1.0
            5110085     0.000217   0.000048          2.0             2.0
            5115085     0.000319   0.000046          1.0             3.0

Grounds found by model: 3 out of 6

In [94]:
# ==========================================
# GENERATE ALL PREDICTIONS FOR A MONTH
# ==========================================

def predict_all_grounds(year, month, gear):

    candidates = fish_geo_valid[
        fish_geo_valid["FISHING_GROUND_CODE"].notna() &
        fish_geo_valid["CENTER_LAT"].notna() &
        fish_geo_valid["CENTER_LON"].notna()
    ][
        [
            "FISHING_GROUND_CODE",
            "CENTER_LAT",
            "CENTER_LON"
        ]
    ].drop_duplicates(
        "FISHING_GROUND_CODE"
    ).copy()

    # SST coverage
    candidates = candidates[
        candidates["CENTER_LAT"].between(
            float(sst.latitude.min()),
            float(sst.latitude.max())
        ) &
        candidates["CENTER_LON"].between(
            float(sst.longitude.min()),
            float(sst.longitude.max())
        )
    ].copy()

    # Find SST dates in requested month
    matching_times = sst_times[
        (sst_times.year == year) &
        (sst_times.month == month)
    ]

    if len(matching_times) == 0:
        return pd.DataFrame()

    target_date = pd.Timestamp(
        year=year,
        month=month,
        day=1
    )

    nearest_time = matching_times[
        np.argmin(
            np.abs(matching_times - target_date)
        )
    ]

    # Extract SST
    def extract_sst(row):
        return float(
            sst["SST"].sel(
                time=nearest_time,
                latitude=row["CENTER_LAT"],
                longitude=row["CENTER_LON"],
                method="nearest"
            ).values
        )

    candidates["SST"] = candidates.apply(
        extract_sst,
        axis=1
    )

    candidates = candidates.dropna(
        subset=["SST"]
    ).copy()

    # Seasonal features
    candidates["MONTH_SIN"] = np.sin(
        2 * np.pi * month / 12
    )

    candidates["MONTH_COS"] = np.cos(
        2 * np.pi * month / 12
    )

    candidates["GEAR"] = gear

    # Predict
    candidates["PRED_LOG_CPUE"] = model.predict(
        candidates[feature_columns]
    )

    candidates["PRED_CPUE"] = np.exp(
        candidates["PRED_LOG_CPUE"]
    )

    # Rank ALL candidates
    candidates = candidates.sort_values(
        "PRED_CPUE",
        ascending=False
    ).reset_index(drop=True)

    candidates["PREDICTED_RANK"] = (
        candidates.index + 1
    )

    return candidates

In [95]:
# ==========================================
# CHECK JANUARY 2012 AGAIN
# ==========================================

all_jan_2012 = predict_all_grounds(
    2012,
    1,
    "Longline (exploratory)"
)

jan_actual = (
    test_df[
        (test_df["YEAR"] == 2012) &
        (test_df["MONTH_START"] == 1)
    ]
    .groupby("FISHING_GROUND_CODE", as_index=False)
    .agg(
        ACTUAL_CPUE=("CPUE", "mean")
    )
)

jan_check = jan_actual.merge(
    all_jan_2012[
        [
            "FISHING_GROUND_CODE",
            "PRED_CPUE",
            "PREDICTED_RANK"
        ]
    ],
    on="FISHING_GROUND_CODE",
    how="left"
)

jan_check["ACTUAL_RANK"] = (
    jan_check["ACTUAL_CPUE"]
    .rank(
        ascending=False,
        method="min"
    )
)

jan_check = jan_check.sort_values(
    "ACTUAL_RANK"
)

print("JANUARY 2012 — ALL OBSERVED GROUNDS")
print("====================================")

print(
    jan_check.to_string(index=False)
)

JANUARY 2012 — ALL OBSERVED GROUNDS
====================================
FISHING_GROUND_CODE  ACTUAL_CPUE  PRED_CPUE  PREDICTED_RANK  ACTUAL_RANK
            5115085     0.000319   0.000046               7          1.0
            5110080     0.000248   0.000022              32          2.0
            5110085     0.000217   0.000048               6          3.0
            5105090     0.000170   0.000029              17          4.0
            5110090     0.000145   0.000081               2          5.0
            5110070     0.000119   0.000029              18          6.0

In [96]:
# ==========================================
# FULL GROUND-LEVEL TEST EVALUATION
# ==========================================

from scipy.stats import spearmanr

evaluation_rows = []

# Evaluate each gear separately
for gear in test_df["GEAR"].unique():

    gear_test = test_df[
        test_df["GEAR"] == gear
    ].copy()

    # Evaluate each available year/month
    for (year, month), group in gear_test.groupby(
        ["YEAR", "MONTH_START"]
    ):

        # Need at least 5 observed grounds
        if group["FISHING_GROUND_CODE"].nunique() < 5:
            continue

        # Actual ground-level CPUE
        actual = (
            group
            .groupby(
                "FISHING_GROUND_CODE",
                as_index=False
            )
            .agg(
                ACTUAL_CPUE=("CPUE", "mean")
            )
        )

        # Generate predictions for ALL candidate grounds
        predicted = predict_all_grounds(
            year,
            month,
            gear
        )

        # Merge actual observations with predictions
        merged = actual.merge(
            predicted[
                [
                    "FISHING_GROUND_CODE",
                    "PRED_CPUE",
                    "PREDICTED_RANK"
                ]
            ],
            on="FISHING_GROUND_CODE",
            how="left"
        )

        # Keep only grounds for which prediction exists
        merged = merged.dropna(
            subset=["PRED_CPUE"]
        )

        if len(merged) < 5:
            continue

        # Rank correlation
        rho, p_value = spearmanr(
            merged["ACTUAL_CPUE"],
            merged["PRED_CPUE"]
        )

        # Actual top 5
        actual_top5 = set(
            merged.nlargest(
                5,
                "ACTUAL_CPUE"
            )["FISHING_GROUND_CODE"]
        )

        # Predicted top 10 from the COMPLETE candidate pool
        predicted_top10 = set(
            predicted.head(10)[
                "FISHING_GROUND_CODE"
            ]
        )

        top5_hits = len(
            actual_top5.intersection(
                predicted_top10
            )
        )

        evaluation_rows.append({
            "YEAR": year,
            "MONTH": month,
            "GEAR": gear,
            "OBSERVED_GROUNDS": len(actual),
            "EVALUATED_GROUNDS": len(merged),
            "SPEARMAN": rho,
            "TOP5_IN_PRED_TOP10": top5_hits
        })


evaluation_df = pd.DataFrame(
    evaluation_rows
)

print("GROUND-LEVEL EVALUATION")
print("=======================")

print(
    evaluation_df.to_string(index=False)
)

print("\n--------------------------------")
print("SUMMARY")
print("--------------------------------")

if len(evaluation_df) > 0:

    print(
        "Evaluation periods:",
        len(evaluation_df)
    )

    print(
        "Average Spearman:",
        round(
            evaluation_df["SPEARMAN"].mean(),
            4
        )
    )

    print(
        "Median Spearman:",
        round(
            evaluation_df["SPEARMAN"].median(),
            4
        )
    )

    print(
        "Average actual Top-5 grounds found in predicted Top-10:",
        round(
            evaluation_df[
                "TOP5_IN_PRED_TOP10"
            ].mean(),
            2
        ),
        "/ 5"
    )

else:
    print(
        "No months had enough observations for evaluation."
    )

GROUND-LEVEL EVALUATION
=======================
 YEAR  MONTH                     GEAR  OBSERVED_GROUNDS  EVALUATED_GROUNDS  SPEARMAN  TOP5_IN_PRED_TOP10
 2012      1 Longline (deep-freezing)                 6                  6  0.714286                   0
 2012      2 Longline (deep-freezing)                 6                  6  0.828571                   2

--------------------------------
SUMMARY
--------------------------------
Evaluation periods: 2
Average Spearman: 0.7714
Median Spearman: 0.7714
Average actual Top-5 grounds found in predicted Top-10: 1.0 / 5

In [97]:
# ==========================================
# HISTORICAL GEAR-SUPPORTED CANDIDATE GROUNDS
# ==========================================

gear_supported = (
    train_df[
        [
            "GEAR",
            "FISHING_GROUND_CODE"
        ]
    ]
    .drop_duplicates()
    .groupby("GEAR")
    ["FISHING_GROUND_CODE"]
    .nunique()
)

print("GEAR-SUPPORTED CANDIDATE GROUNDS")
print("================================")

print(gear_supported)

print("\nGrounds by gear:")

for gear in train_df["GEAR"].unique():

    grounds = (
        train_df[
            train_df["GEAR"] == gear
        ]["FISHING_GROUND_CODE"]
        .unique()
    )

    print(
        f"\n{gear}: {len(grounds)} grounds"
    )

GEAR-SUPPORTED CANDIDATE GROUNDS
================================
GEAR
Longline (deep-freezing)    12
Longline (exploratory)      28
Name: FISHING_GROUND_CODE, dtype: int64

Grounds by gear:

Longline (exploratory): 28 grounds

Longline (deep-freezing): 12 grounds

In [98]:
# ==========================================
# PREDICT USING ONLY GEAR-SUPPORTED GROUNDS
# ==========================================

def predict_supported_grounds(year, month, gear):

    # Grounds historically used with this gear
    supported_grounds = set(
        train_df[
            train_df["GEAR"] == gear
        ]["FISHING_GROUND_CODE"]
        .unique()
    )

    candidates = fish_geo_valid[
        fish_geo_valid["FISHING_GROUND_CODE"].isin(
            supported_grounds
        )
    ][
        [
            "FISHING_GROUND_CODE",
            "CENTER_LAT",
            "CENTER_LON"
        ]
    ].drop_duplicates(
        "FISHING_GROUND_CODE"
    ).copy()

    # Keep grounds inside SST coverage
    candidates = candidates[
        candidates["CENTER_LAT"].between(
            float(sst.latitude.min()),
            float(sst.latitude.max())
        ) &
        candidates["CENTER_LON"].between(
            float(sst.longitude.min()),
            float(sst.longitude.max())
        )
    ].copy()

    # Find SST dates for requested month
    matching_times = sst_times[
        (sst_times.year == year) &
        (sst_times.month == month)
    ]

    if len(matching_times) == 0:
        return pd.DataFrame()

    target_date = pd.Timestamp(
        year=year,
        month=month,
        day=1
    )

    nearest_time = matching_times[
        np.argmin(
            np.abs(matching_times - target_date)
        )
    ]

    # Extract SST
    def extract_sst(row):

        value = sst["SST"].sel(
            time=nearest_time,
            latitude=row["CENTER_LAT"],
            longitude=row["CENTER_LON"],
            method="nearest"
        ).values

        return float(value)

    candidates["SST"] = candidates.apply(
        extract_sst,
        axis=1
    )

    # Remove missing SST
    candidates = candidates.dropna(
        subset=["SST"]
    ).copy()

    # Seasonal features
    candidates["MONTH_SIN"] = np.sin(
        2 * np.pi * month / 12
    )

    candidates["MONTH_COS"] = np.cos(
        2 * np.pi * month / 12
    )

    candidates["GEAR"] = gear

    # Predict
    candidates["PRED_LOG_CPUE"] = model.predict(
        candidates[feature_columns]
    )

    candidates["PRED_CPUE"] = np.exp(
        candidates["PRED_LOG_CPUE"]
    )

    # Rank
    candidates = candidates.sort_values(
        "PRED_CPUE",
        ascending=False
    ).reset_index(drop=True)

    candidates["PREDICTED_RANK"] = (
        candidates.index + 1
    )

    return candidates

In [99]:
# ==========================================
# JANUARY 2012 — SUPPORTED GROUNDS ONLY
# ==========================================

supported_jan = predict_supported_grounds(
    2012,
    1,
    "Longline (exploratory)"
)

print(
    "SUPPORTED-GROUND PREDICTIONS — JANUARY 2012"
)
print("============================================")

print(
    supported_jan.to_string(index=False)
)

SUPPORTED-GROUND PREDICTIONS — JANUARY 2012
============================================
FISHING_GROUND_CODE  CENTER_LAT  CENTER_LON       SST  MONTH_SIN  MONTH_COS                   GEAR  PRED_LOG_CPUE  PRED_CPUE  PREDICTED_RANK
            5110088   10.500000   88.500000 27.900000        0.5   0.866025 Longline (exploratory)      -9.401941   0.000083               1
            5110090   10.500000   90.500000 28.350000        0.5   0.866025 Longline (exploratory)      -9.420729   0.000081               2
            5110093   10.500000   93.500000 28.049999        0.5   0.866025 Longline (exploratory)      -9.519382   0.000073               3
            6115090   17.368863   92.184274 27.600000        0.5   0.866025 Longline (exploratory)      -9.656273   0.000064               4
            6115080   16.365458   83.268322 27.900000        0.5   0.866025 Longline (exploratory)      -9.945543   0.000048               5
            5110085   10.500000   85.500000 27.750000        0.5   0.866025 Longline (exploratory)      -9.946553   0.000048               6
            5115085   15.500000   85.500000 27.900000        0.5   0.866025 Longline (exploratory)      -9.983464   0.000046               7
            6105090    7.499989   92.493752 29.700001        0.5   0.866025 Longline (exploratory)     -10.009956   0.000045               8
            6110085   12.500000   87.500000 27.600000        0.5   0.866025 Longline (exploratory)     -10.076685   0.000042               9
            6115085   17.461143   87.534336 26.850000        0.5   0.866025 Longline (exploratory)     -10.085852   0.000042              10
            6110080   12.476727   82.554531 27.750000        0.5   0.866025 Longline (exploratory)     -10.226114   0.000036              11
            6100090    2.500000   92.500000 29.850000        0.5   0.866025 Longline (exploratory)     -10.430779   0.000030              12
            5110071   10.500000   71.500000 28.799999        0.5   0.866025 Longline (exploratory)     -10.465817   0.000028              13
            5110066   10.500000   66.500000 28.650000        0.5   0.866025 Longline (exploratory)     -10.494816   0.000028              14
            5119067   19.500000   67.500000 26.400000        0.5   0.866025 Longline (exploratory)     -10.524201   0.000027              15
            5105088    5.500000   88.500000 30.000000        0.5   0.866025 Longline (exploratory)     -10.546722   0.000026              16
            6115065   17.500000   67.500000 26.700001        0.5   0.866025 Longline (exploratory)     -10.561183   0.000026              17
            5105093    5.500000   93.500000 30.900000        0.5   0.866025 Longline (exploratory)     -10.585342   0.000025              18
            5115066   15.500000   66.500000 26.700001        0.5   0.866025 Longline (exploratory)     -10.723321   0.000022              19
            5115071   15.500000   71.500000 28.200001        0.5   0.866025 Longline (exploratory)     -10.726124   0.000022              20
            5110080   10.500000   80.500000 28.500000        0.5   0.866025 Longline (exploratory)     -10.729611   0.000022              21
            5105071    5.500000   71.500000 28.799999        0.5   0.866025 Longline (exploratory)     -10.802720   0.000020              22
            6110065   12.500000   67.500000 28.200001        0.5   0.866025 Longline (exploratory)     -10.805690   0.000020              23
            5114067   14.500000   67.500000 27.600000        0.5   0.866025 Longline (exploratory)     -10.807525   0.000020              24
            6115070   17.337561   71.614762 28.350000        0.5   0.866025 Longline (exploratory)     -10.817127   0.000020              25
            6110070   12.424875   72.399294 28.650000        0.5   0.866025 Longline (exploratory)     -11.014902   0.000016              26
            6105070    7.500153   72.499889 28.650000        0.5   0.866025 Longline (exploratory)     -11.044451   0.000016              27
            5105076    5.500000   76.500000 28.350000        0.5   0.866025 Longline (exploratory)     -11.123756   0.000015              28

In [100]:
# ==========================================
# SUPPORTED GROUNDS vs ACTUAL — JAN 2012
# ==========================================

jan_actual_supported = (
    test_df[
        (test_df["YEAR"] == 2012) &
        (test_df["MONTH_START"] == 1) &
        (test_df["GEAR"] == "Longline (exploratory)")
    ]
    .groupby("FISHING_GROUND_CODE", as_index=False)
    .agg(
        ACTUAL_CPUE=("CPUE", "mean")
    )
)

jan_compare = jan_actual_supported.merge(
    supported_jan[
        [
            "FISHING_GROUND_CODE",
            "PRED_CPUE",
            "PREDICTED_RANK"
        ]
    ],
    on="FISHING_GROUND_CODE",
    how="left"
)

jan_compare["ACTUAL_RANK"] = (
    jan_compare["ACTUAL_CPUE"]
    .rank(
        ascending=False,
        method="min"
    )
)

jan_compare = jan_compare.sort_values(
    "ACTUAL_RANK"
)

print("JANUARY 2012 — SUPPORTED GROUNDS")
print("=================================")

print(
    jan_compare.to_string(index=False)
)

# Ranking correlation
valid = jan_compare.dropna(
    subset=["PRED_CPUE"]
)

if len(valid) >= 3:
    rho, p = spearmanr(
        valid["ACTUAL_CPUE"],
        valid["PRED_CPUE"]
    )

    print("\nSpearman correlation:",
          round(rho, 4))

print(
    "\nActual grounds:",
    len(jan_actual_supported)
)

print(
    "Actual grounds with predictions:",
    len(valid)
)

JANUARY 2012 — SUPPORTED GROUNDS
=================================
FISHING_GROUND_CODE  ACTUAL_CPUE  PRED_CPUE  PREDICTED_RANK  ACTUAL_RANK
            5110070     0.000015        NaN             NaN          1.0

Actual grounds: 1
Actual grounds with predictions: 0

In [101]:
# ==========================================
# JANUARY 2012 — CHECK GEAR DISTRIBUTION
# ==========================================

jan2012 = test_df[
    (test_df["YEAR"] == 2012) &
    (test_df["MONTH_START"] == 1)
].copy()

print("JANUARY 2012 TEST OBSERVATIONS")
print("==============================")

print("\nNumber of observations:", len(jan2012))

print("\nGear distribution:")
print(
    jan2012["GEAR"].value_counts()
)

print("\nGrounds by gear:")
print(
    jan2012[
        [
            "FISHING_GROUND_CODE",
            "GEAR",
            "CPUE"
        ]
    ]
    .sort_values("CPUE", ascending=False)
    .to_string(index=False)
)

JANUARY 2012 TEST OBSERVATIONS
==============================

Number of observations: 7

Gear distribution:
GEAR
Longline (deep-freezing)    6
Longline (exploratory)      1
Name: count, dtype: int64

Grounds by gear:
FISHING_GROUND_CODE                     GEAR     CPUE
            5115085 Longline (deep-freezing) 0.000319
            5110080 Longline (deep-freezing) 0.000248
            5110070 Longline (deep-freezing) 0.000223
            5110085 Longline (deep-freezing) 0.000217
            5105090 Longline (deep-freezing) 0.000170
            5110090 Longline (deep-freezing) 0.000145
            5110070   Longline (exploratory) 0.000015

In [102]:
# ==========================================
# JANUARY 2012 — CORRECT GEAR EVALUATION
# ==========================================

gear = "Longline (deep-freezing)"

# Generate predictions for grounds historically
# supported by deep-freezing fishing
supported_jan_deep = predict_supported_grounds(
    2012,
    1,
    gear
)

# Actual January 2012 observations for this gear
actual_jan_deep = (
    test_df[
        (test_df["YEAR"] == 2012) &
        (test_df["MONTH_START"] == 1) &
        (test_df["GEAR"] == gear)
    ]
    .groupby("FISHING_GROUND_CODE", as_index=False)
    .agg(
        ACTUAL_CPUE=("CPUE", "mean")
    )
)

# Merge actual and predicted
jan_deep_compare = actual_jan_deep.merge(
    supported_jan_deep[
        [
            "FISHING_GROUND_CODE",
            "PRED_CPUE",
            "PREDICTED_RANK"
        ]
    ],
    on="FISHING_GROUND_CODE",
    how="left"
)

# Actual ranking
jan_deep_compare["ACTUAL_RANK"] = (
    jan_deep_compare["ACTUAL_CPUE"]
    .rank(
        ascending=False,
        method="min"
    )
)

jan_deep_compare = jan_deep_compare.sort_values(
    "ACTUAL_RANK"
)

print("JANUARY 2012 — DEEP-FREEZING")
print("=============================")

print(
    jan_deep_compare.to_string(index=False)
)

print(
    "\nActual grounds:",
    len(actual_jan_deep)
)

print(
    "Grounds with predictions:",
    jan_deep_compare["PRED_CPUE"].notna().sum()
)

# Spearman ranking
valid = jan_deep_compare.dropna(
    subset=["PRED_CPUE"]
)

if len(valid) >= 3:

    rho, p = spearmanr(
        valid["ACTUAL_CPUE"],
        valid["PRED_CPUE"]
    )

    print(
        "\nSpearman correlation:",
        round(rho, 4)
    )

JANUARY 2012 — DEEP-FREEZING
=============================
FISHING_GROUND_CODE  ACTUAL_CPUE  PRED_CPUE  PREDICTED_RANK  ACTUAL_RANK
            5115085     0.000319        NaN             NaN          1.0
            5110080     0.000248        NaN             NaN          2.0
            5110070     0.000223        NaN             NaN          3.0
            5110085     0.000217        NaN             NaN          4.0
            5105090     0.000170        NaN             NaN          5.0
            5110090     0.000145        NaN             NaN          6.0

Actual grounds: 6
Grounds with predictions: 0

In [103]:
# ==========================================
# WHY ARE DEEP-FREEZING GROUNDS DISAPPEARING?
# ==========================================

gear = "Longline (deep-freezing)"

supported = (
    train_df[
        train_df["GEAR"] == gear
    ]["FISHING_GROUND_CODE"]
    .unique()
)

check = (
    fish_geo_valid[
        fish_geo_valid["FISHING_GROUND_CODE"].isin(supported)
    ][
        [
            "FISHING_GROUND_CODE",
            "CENTER_LAT",
            "CENTER_LON"
        ]
    ]
    .drop_duplicates("FISHING_GROUND_CODE")
    .copy()
)

# Check whether each ground is inside SST spatial coverage
check["INSIDE_SST_AREA"] = (
    check["CENTER_LAT"].between(
        float(sst.latitude.min()),
        float(sst.latitude.max())
    )
    &
    check["CENTER_LON"].between(
        float(sst.longitude.min()),
        float(sst.longitude.max())
    )
)

print("DEEP-FREEZING SUPPORTED GROUNDS")
print("================================")

print(
    check.to_string(index=False)
)

print("\nTotal supported grounds:", len(check))

print(
    "Inside SST coverage:",
    check["INSIDE_SST_AREA"].sum()
)

print(
    "Outside SST coverage:",
    (~check["INSIDE_SST_AREA"]).sum()
)

print("\nSST coverage:")
print(
    "Latitude:",
    float(sst.latitude.min()),
    "to",
    float(sst.latitude.max())
)

print(
    "Longitude:",
    float(sst.longitude.min()),
    "to",
    float(sst.longitude.max())
)

DEEP-FREEZING SUPPORTED GROUNDS
================================
FISHING_GROUND_CODE  CENTER_LAT  CENTER_LON  INSIDE_SST_AREA
            6100080    2.500000   82.500000             True
            6105070    7.500153   72.499889             True
            6105085    7.500000   87.500000             True
            6105090    7.499989   92.493752             True
            6110070   12.424875   72.399294             True
            6110080   12.476727   82.554531             True
            6110085   12.500000   87.500000             True
            6115065   17.500000   67.500000             True
            6115070   17.337561   71.614762             True
            6115080   16.365458   83.268322             True
            6115085   17.461143   87.534336             True
            6115090   17.368863   92.184274             True

Total supported grounds: 12
Inside SST coverage: 12
Outside SST coverage: 0

SST coverage:
Latitude: 2.5 to 20.0
Longitude: 65.5 to 95.5

In [104]:
# ==========================================
# TRAIN vs TEST FISHING-GROUND OVERLAP
# ==========================================

for gear in test_df["GEAR"].unique():

    train_grounds = set(
        train_df[
            train_df["GEAR"] == gear
        ]["FISHING_GROUND_CODE"]
        .unique()
    )

    test_grounds = set(
        test_df[
            test_df["GEAR"] == gear
        ]["FISHING_GROUND_CODE"]
        .unique()
    )

    overlap = train_grounds.intersection(
        test_grounds
    )

    unseen = test_grounds - train_grounds

    print("\nGEAR:", gear)
    print("-----------------------------")

    print(
        "Training grounds:",
        len(train_grounds)
    )

    print(
        "Test grounds:",
        len(test_grounds)
    )

    print(
        "Grounds seen in BOTH:",
        len(overlap)
    )

    print(
        "Test-only unseen grounds:",
        len(unseen)
    )

    print(
        "\nOverlapping grounds:",
        sorted(overlap)
    )

    print(
        "\nUnseen test grounds:",
        sorted(unseen)
    )

GEAR: Longline (deep-freezing)
-----------------------------
Training grounds: 12
Test grounds: 8
Grounds seen in BOTH: 0
Test-only unseen grounds: 8

Overlapping grounds: []

Unseen test grounds: ['5105090', '5110070', '5110080', '5110085', '5110090', '5115065', '5115070', '5115085']

GEAR: Longline (exploratory)
-----------------------------
Training grounds: 28
Test grounds: 7
Grounds seen in BOTH: 3
Test-only unseen grounds: 4

Overlapping grounds: ['5110080', '5110090', '5115085']

Unseen test grounds: ['5105090', '5110070', '5115065', '5115070']

In [105]:
# ==========================================
# TEMPORAL GENERALIZATION AT KNOWN GROUNDS
# ==========================================

gear = "Longline (exploratory)"

train_grounds = set(
    train_df[
        train_df["GEAR"] == gear
    ]["FISHING_GROUND_CODE"]
)

test_known = test_df[
    (test_df["GEAR"] == gear) &
    (test_df["FISHING_GROUND_CODE"].isin(train_grounds))
].copy()

print("KNOWN-GROUND TEMPORAL TEST")
print("==========================")

print(
    "Test observations:",
    len(test_known)
)

print(
    "Known grounds:",
    test_known["FISHING_GROUND_CODE"].nunique()
)

print(
    "Grounds:",
    sorted(
        test_known["FISHING_GROUND_CODE"].unique()
    )
)

# Actual vs predicted
X_known = test_known[feature_columns]

known_pred_log = model.predict(X_known)

test_known["PRED_LOG_CPUE"] = known_pred_log

test_known["PRED_CPUE"] = np.exp(
    known_pred_log
)

# Ground-level aggregation
known_ground = (
    test_known
    .groupby(
        "FISHING_GROUND_CODE",
        as_index=False
    )
    .agg(
        ACTUAL_CPUE=("CPUE", "mean"),
        PRED_CPUE=("PRED_CPUE", "mean")
    )
)

print("\nGROUND-LEVEL RESULTS")
print("====================")

print(
    known_ground.to_string(index=False)
)

# Correlation
if len(known_ground) >= 3:

    rho, p = spearmanr(
        known_ground["ACTUAL_CPUE"],
        known_ground["PRED_CPUE"]
    )

    print(
        "\nSpearman correlation:",
        round(rho, 4)
    )

KNOWN-GROUND TEMPORAL TEST
==========================
Test observations: 17
Known grounds: 3
Grounds: ['5110080', '5110090', '5115085']

GROUND-LEVEL RESULTS
====================
FISHING_GROUND_CODE  ACTUAL_CPUE  PRED_CPUE
            5110080     0.000046   0.000026
            5110090     0.000019   0.000047
            5115085     0.000124   0.000032

Spearman correlation: -0.5

In [106]:
import os

print("Current directory:")
print(os.getcwd())

print("\nFiles in /content:")
print(os.listdir("/content"))

Current directory:
/content

Files in /content:
['.config', 'drive', 'sample_data']

In [107]:
import os

print(os.listdir("/content/drive/MyDrive"))

['College Shit', 'Semester - 1 ', 'Main Projects ', 'Colab Notebooks', 'DATASETS', 'IOTC-2026-WPB24-DATA03_CE.zip']

In [108]:
import zipfile

billfish_zip = "/content/drive/MyDrive/IOTC-2026-WPB24-DATA03_CE.zip"

with zipfile.ZipFile(billfish_zip) as z:
    print("Files inside ZIP:")
    for f in z.namelist():
        print(f)

Files inside ZIP:
IOTC-2026-WPB24-DATA03_CA.csv
IOTC-2026-WPB24-DATA03_EF.csv

In [109]:
import zipfile
import pandas as pd

billfish_zip = "/content/drive/MyDrive/IOTC-2026-WPB24-DATA03_CE.zip"

with zipfile.ZipFile(billfish_zip) as z:
    with z.open("IOTC-2026-WPB24-DATA03_CA.csv") as f:
        billfish_catch = pd.read_csv(f)

print("Shape:", billfish_catch.shape)
print("\nColumns:")
print(billfish_catch.columns.tolist())

print("\nFirst 5 rows:")
display(billfish_catch.head())

Shape: (521177, 31)

Columns:
['YEAR', 'MONTH_START', 'MONTH_END', 'FISHING_GROUND_CODE', 'FLEET_CODE', 'FLEET', 'FISHERY_TYPE_CODE', 'FISHERY_TYPE', 'FISHERY_GROUP_CODE', 'FISHERY_GROUP', 'FISHERY_CODE', 'FISHERY', 'GEAR_CODE', 'GEAR', 'CATCH_SCHOOL_TYPE_CODE', 'SPECIES_CATEGORY', 'SPECIES_CATEGORY_CODE', 'SPECIES_CODE', 'SPECIES', 'SPECIES_SCIENTIFIC', 'IS_IOTC_SPECIES', 'IS_SPECIES_AGGREGATE', 'IS_SSI', 'FATE_TYPE_CODE', 'FATE_TYPE', 'FATE_CODE', 'FATE', 'RAISE_CODE', 'RAISING', 'CATCH_UNIT_CODE', 'CATCH']

First 5 rows:

,YEAR,MONTH_START,MONTH_END,FISHING_GROUND_CODE,FLEET_CODE,FLEET,FISHERY_TYPE_CODE,FISHERY_TYPE,FISHERY_GROUP_CODE,FISHERY_GROUP,...,IS_SPECIES_AGGREGATE,IS_SSI,FATE_TYPE_CODE,FATE_TYPE,FATE_CODE,FATE,RAISE_CODE,RAISING,CATCH_UNIT_CODE,CATCH
0,1952,11,11,6210115,JPN,Japan,IND,Industrial fisheries,LL,Longline,...,False,True,RETAINED,Retained,RFL,Retained - for landing / sale,SD,Raised data,NO,535.0
1,1952,11,11,6210115,JPN,Japan,IND,Industrial fisheries,LL,Longline,...,False,True,RETAINED,Retained,RFL,Retained - for landing / sale,SD,Raised data,NO,1277.0
2,1952,11,11,6210115,JPN,Japan,IND,Industrial fisheries,LL,Longline,...,False,True,RETAINED,Retained,RFL,Retained - for landing / sale,SD,Raised data,NO,514.0
3,1952,11,11,6210115,JPN,Japan,IND,Industrial fisheries,LL,Longline,...,False,False,RETAINED,Retained,RFL,Retained - for landing / sale,SD,Raised data,NO,21.0
4,1952,11,11,6210120,JPN,Japan,IND,Industrial fisheries,LL,Longline,...,False,True,RETAINED,Retained,RFL,Retained - for landing / sale,SD,Raised data,NO,836.0

In [110]:
# How many Billfish catch records belong to India?
india_billfish = billfish_catch[
    billfish_catch["FLEET_CODE"] == "IND"
].copy()

print("India Billfish rows:", len(india_billfish))

print("\nYears:")
print(india_billfish["YEAR"].min(), "to", india_billfish["YEAR"].max())

print("\nUnique fishing grounds:")
print(india_billfish["FISHING_GROUND_CODE"].nunique())

print("\nSpecies-related columns:")
print([c for c in billfish_catch.columns if "SPECIES" in c.upper()])

India Billfish rows: 701

Years:
1991 to 2021

Unique fishing grounds:
56

Species-related columns:
['SPECIES_CATEGORY', 'SPECIES_CATEGORY_CODE', 'SPECIES_CODE', 'SPECIES', 'SPECIES_SCIENTIFIC', 'IS_IOTC_SPECIES', 'IS_SPECIES_AGGREGATE']

In [111]:
print("Billfish species in India:\n")

print(
    india_billfish["SPECIES"]
    .value_counts(dropna=False)
)

print("\nSpecies codes:")
print(
    india_billfish[
        ["SPECIES_CODE", "SPECIES"]
    ].drop_duplicates().sort_values("SPECIES_CODE")
)

Billfish species in India:

SPECIES
Swordfish                313
Indo-Pacific sailfish    224
Black marlin              93
Blue marlin               68
Striped marlin             3
Name: count, dtype: int64

Species codes:
       SPECIES_CODE                SPECIES
293789          BLM           Black marlin
226210          BUM            Blue marlin
329022          MLS         Striped marlin
148570          SFA  Indo-Pacific sailfish
148521          SWO              Swordfish

In [112]:
print("Billfish records by year:")
print(
    india_billfish["YEAR"]
    .value_counts()
    .sort_index()
)

Billfish records by year:
YEAR
1991     25
1994      6
1995     35
1996     19
1997     19
2002      7
2003     18
2004     22
2005     16
2006     17
2007     32
2008     20
2009     51
2010     51
2011    118
2012     57
2013     57
2014     20
2015     53
2018     46
2020      3
2021      9
Name: count, dtype: int64

In [113]:
print("\nBillfish records by month:")
print(
    india_billfish["MONTH_START"]
    .value_counts()
    .sort_index()
)

Billfish records by month:
MONTH_START
1     125
2      75
3      97
4      71
5      41
6      27
7      32
8      28
9      33
10     49
11     67
12     56
Name: count, dtype: int64

In [114]:
with zipfile.ZipFile(billfish_zip) as z:
    with z.open("IOTC-2026-WPB24-DATA03_EF.csv") as f:
        billfish_effort = pd.read_csv(f)

print("Effort shape:", billfish_effort.shape)

print("\nColumns:")
print(billfish_effort.columns.tolist())

print("\nIndia effort rows:",
      (billfish_effort["FLEET_CODE"] == "IND").sum())

Effort shape: (668357, 17)

Columns:
['YEAR', 'MONTH_START', 'MONTH_END', 'FISHING_GROUND_CODE', 'FLEET_CODE', 'FLEET', 'FISHERY_TYPE_CODE', 'FISHERY_TYPE', 'FISHERY_GROUP_CODE', 'FISHERY_GROUP', 'FISHERY_CODE', 'FISHERY', 'GEAR_CODE', 'GEAR', 'SCHOOL_TYPE_CODE', 'EFFORT_UNIT_CODE', 'EFFORT']

India effort rows: 1196

In [115]:
# Filter India effort
india_billfish_effort = billfish_effort[
    billfish_effort["FLEET_CODE"] == "IND"
].copy()

# Keys used to match catch with effort
merge_keys = [
    "YEAR",
    "MONTH_START",
    "MONTH_END",
    "FISHING_GROUND_CODE",
    "FLEET_CODE",
    "FISHERY_TYPE_CODE",
    "FISHERY_GROUP_CODE",
    "FISHERY_CODE",
    "GEAR_CODE"
]

# Check uniqueness of effort records
print("Effort rows:", len(india_billfish_effort))
print("Unique effort keys:",
      india_billfish_effort[merge_keys].drop_duplicates().shape[0])

# Aggregate catch first
billfish_catch_agg = (
    india_billfish
    .groupby(merge_keys, as_index=False)
    .agg(TOTAL_CATCH_MT=("CATCH", "sum"))
)

print("\nAggregated catch rows:", len(billfish_catch_agg))

# Match catch to effort
billfish_merged = billfish_catch_agg.merge(
    india_billfish_effort[
        merge_keys + ["EFFORT_UNIT_CODE", "EFFORT"]
    ],
    on=merge_keys,
    how="left",
    indicator=True
)

print("\nCatch records matched to effort:")
print(billfish_merged["_merge"].value_counts())

Effort rows: 1196
Unique effort keys: 1196

Aggregated catch rows: 480

Catch records matched to effort:
_merge
both          480
left_only       0
right_only      0
Name: count, dtype: int64

In [116]:
# Calculate CPUE
billfish_merged["CPUE"] = (
    billfish_merged["TOTAL_CATCH_MT"] /
    billfish_merged["EFFORT"]
)

# Add species back to the aggregated records
species_lookup = (
    india_billfish
    .groupby(merge_keys)["SPECIES"]
    .agg(lambda x: ", ".join(sorted(x.unique())))
    .reset_index()
)

billfish_model = billfish_merged.merge(
    species_lookup,
    on=merge_keys,
    how="left"
)

# Remove invalid CPUE
billfish_model = billfish_model[
    (billfish_model["EFFORT"] > 0) &
    (billfish_model["CPUE"] > 0)
].copy()

print("Billfish model rows:", len(billfish_model))
print("Years:", billfish_model["YEAR"].min(), "to", billfish_model["YEAR"].max())
print("Unique grounds:", billfish_model["FISHING_GROUND_CODE"].nunique())

print("\nSpecies:")
print(billfish_model["SPECIES"].value_counts())

print("\nEffort units:")
print(billfish_model["EFFORT_UNIT_CODE"].value_counts())

Billfish model rows: 480
Years: 1991 to 2021
Unique grounds: 56

Species:
SPECIES
Swordfish                                                      184
Indo-Pacific sailfish                                           76
Indo-Pacific sailfish, Swordfish                                63
Black marlin, Indo-Pacific sailfish                             33
Blue marlin                                                     31
Black marlin, Indo-Pacific sailfish, Swordfish                  29
Black marlin, Swordfish                                         13
Blue marlin, Swordfish                                          13
Black marlin                                                    11
Blue marlin, Indo-Pacific sailfish                              11
Blue marlin, Indo-Pacific sailfish, Swordfish                    6
Black marlin, Blue marlin, Indo-Pacific sailfish, Swordfish      3
Black marlin, Blue marlin                                        2
Indo-Pacific sailfish, Striped marlin                            1
Black marlin, Blue marlin, Swordfish                             1
Striped marlin                                                   1
Black marlin, Blue marlin, Indo-Pacific sailfish                 1
Indo-Pacific sailfish, Striped marlin, Swordfish                 1
Name: count, dtype: int64

Effort units:
EFFORT_UNIT_CODE
HOOKS    480
Name: count, dtype: int64

In [117]:
# Make both fishing-ground codes the same type
billfish_model["FISHING_GROUND_CODE"] = (
    billfish_model["FISHING_GROUND_CODE"].astype(str)
)

grid["CODE"] = grid["CODE"].astype(str)

# Add coordinates
billfish_geo = billfish_model.merge(
    grid[["CODE", "CENTER_LAT", "CENTER_LON"]],
    left_on="FISHING_GROUND_CODE",
    right_on="CODE",
    how="left"
)

print("Billfish rows:", len(billfish_geo))

print(
    "Missing coordinates:",
    billfish_geo[["CENTER_LAT", "CENTER_LON"]]
    .isna()
    .any(axis=1)
    .sum()
)

print(
    "Unique grounds with coordinates:",
    billfish_geo.dropna(
        subset=["CENTER_LAT", "CENTER_LON"]
    )["FISHING_GROUND_CODE"].nunique()
)

Billfish rows: 480
Missing coordinates: 43
Unique grounds with coordinates: 52

In [118]:
billfish_train = billfish_geo[
    billfish_geo["YEAR"].between(2005, 2014)
].dropna(
    subset=["CENTER_LAT", "CENTER_LON"]
).copy()

print("Billfish training rows:", len(billfish_train))
print("Unique grounds:", billfish_train["FISHING_GROUND_CODE"].nunique())
print("Years:", billfish_train["YEAR"].min(), "to", billfish_train["YEAR"].max())
print("\nRows by year:")
print(billfish_train["YEAR"].value_counts().sort_index())

Billfish training rows: 287
Unique grounds: 43
Years: 2005 to 2014

Rows by year:
YEAR
2005    15
2006    17
2007    26
2008    17
2009    36
2010    35
2011    57
2012    32
2013    36
2014    16
Name: count, dtype: int64

In [119]:
import xarray as xr

sst_path = "/content/drive/MyDrive/DATASETS/incois_tmi_sst_2005_2014_indian_ocean.nc"

ds = xr.open_dataset(sst_path)

print(ds)

<xarray.Dataset> Size: 13MB
Dimensions:    (time: 365, latitude: 71, longitude: 121)
Coordinates:
  * time       (time) datetime64[ns] 3kB 2005-01-01 2005-01-11 ... 2014-12-22
  * latitude   (latitude) float64 568B 2.5 2.75 3.0 3.25 ... 19.5 19.75 20.0
  * longitude  (longitude) float64 968B 65.5 65.75 66.0 ... 95.0 95.25 95.5
Data variables:
    SST        (time, latitude, longitude) float32 13MB ...
Attributes: (12/26)
    cdm_data_type:              Grid
    Conventions:                CF-1.6, COARDS, ACDD-1.3
    Easternmost_Easting:        95.5
    geospatial_lat_max:         20.0
    geospatial_lat_min:         2.5
    geospatial_lat_resolution:  0.25
    ...                         ...
    standard_name_vocabulary:   CF Standard Name Table v29
    summary:                    INCOIS TMI 3Day Data
    time_coverage_end:          2014-12-22T00:00:00Z
    time_coverage_start:        2005-01-01T00:00:00Z
    title:                      INCOIS TMI 3Day Data
    Westernmost_Easting:        65.5

In [120]:
import numpy as np

def get_sst(row):
    month_data = ds.sel(
        time=ds.time.where(
            (ds.time.dt.year == row["YEAR"]) &
            (ds.time.dt.month == row["MONTH_START"]),
            drop=True
        )
    )

    if len(month_data.time) == 0:
        return np.nan

    point = month_data["SST"].sel(
        latitude=row["CENTER_LAT"],
        longitude=row["CENTER_LON"],
        method="nearest"
    )

    return float(point.mean(skipna=True).values)


billfish_train["SST"] = billfish_train.apply(get_sst, axis=1)

print("Billfish rows:", len(billfish_train))
print("Valid SST:", billfish_train["SST"].notna().sum())
print("Missing SST:", billfish_train["SST"].isna().sum())

Billfish rows: 287
Valid SST: 208
Missing SST: 79

In [123]:
import numpy as np
import pandas as pd

# ---------- Fix merge key type ----------
billfish_train["FISHING_GROUND_CODE"] = (
    billfish_train["FISHING_GROUND_CODE"].astype(str)
)

india_billfish_effort["FISHING_GROUND_CODE"] = (
    india_billfish_effort["FISHING_GROUND_CODE"].astype(str)
)

# ---------- Add GEAR to Billfish ----------
gear_lookup = (
    india_billfish_effort[
        merge_keys + ["GEAR"]
    ]
    .drop_duplicates(merge_keys)
)

billfish_train = billfish_train.drop(
    columns=["GEAR"],
    errors="ignore"
)

billfish_train = billfish_train.merge(
    gear_lookup,
    on=merge_keys,
    how="left"
)

# ---------- Tropical Tuna ----------
tuna_model = fish_sst_valid.copy()
tuna_model["SPECIES_GROUP"] = "TUNA"

# ---------- Billfish ----------
bill_model = billfish_train[
    billfish_train["SST"].notna()
].copy()

bill_model["SPECIES_GROUP"] = "BILLFISH"

# ---------- Keep common columns ----------
cols = [
    "YEAR", "MONTH_START",
    "FISHING_GROUND_CODE",
    "CENTER_LAT", "CENTER_LON",
    "GEAR", "SST", "CPUE",
    "SPECIES_GROUP"
]

tuna_model = tuna_model[cols]
bill_model = bill_model[cols]

# ---------- Combine ----------
combined = pd.concat(
    [tuna_model, bill_model],
    ignore_index=True
)

combined = combined[
    (combined["CPUE"] > 0) &
    (combined["SST"].notna()) &
    (combined["GEAR"].notna())
].copy()

# ---------- Target ----------
combined["LOG_CPUE"] = np.log(combined["CPUE"])

# ---------- Seasonal features ----------
combined["MONTH_SIN"] = np.sin(
    2 * np.pi * combined["MONTH_START"] / 12
)

combined["MONTH_COS"] = np.cos(
    2 * np.pi * combined["MONTH_START"] / 12
)

# ---------- Check ----------
print("Combined rows:", len(combined))

print("\nSpecies groups:")
print(combined["SPECIES_GROUP"].value_counts())

print("\nGear:")
print(combined["GEAR"].value_counts())

print(
    "\nUnique grounds:",
    combined["FISHING_GROUND_CODE"].nunique()
)

Combined rows: 498

Species groups:
SPECIES_GROUP
TUNA        290
BILLFISH    208
Name: count, dtype: int64

Gear:
GEAR
Longline (exploratory)      368
Longline (deep-freezing)    130
Name: count, dtype: int64

Unique grounds: 42

In [124]:
# Make the merge key consistent
billfish_train["FISHING_GROUND_CODE"] = (
    billfish_train["FISHING_GROUND_CODE"].astype(str)
)

india_billfish_effort["FISHING_GROUND_CODE"] = (
    india_billfish_effort["FISHING_GROUND_CODE"].astype(str)
)

# Get gear information
gear_lookup = (
    india_billfish_effort[
        merge_keys + ["GEAR"]
    ]
    .drop_duplicates(merge_keys)
)

# Remove GEAR if it already exists
billfish_train = billfish_train.drop(
    columns=["GEAR"],
    errors="ignore"
)

# Merge gear
billfish_train = billfish_train.merge(
    gear_lookup,
    on=merge_keys,
    how="left"
)

print("Rows:", len(billfish_train))
print("\nMissing gear:", billfish_train["GEAR"].isna().sum())
print("\nGear:")
print(billfish_train["GEAR"].value_counts())

Rows: 287

Missing gear: 0

Gear:
GEAR
Longline (exploratory)      208
Longline (deep-freezing)     79
Name: count, dtype: int64

In [125]:
# ---------- Prepare Tuna ----------
tuna_model = fish_sst_valid.copy()
tuna_model["SPECIES_GROUP"] = "TUNA"

# ---------- Prepare Billfish ----------
bill_model = billfish_train[
    billfish_train["SST"].notna()
].copy()
bill_model["SPECIES_GROUP"] = "BILLFISH"

# Common columns
cols = [
    "YEAR",
    "MONTH_START",
    "FISHING_GROUND_CODE",
    "CENTER_LAT",
    "CENTER_LON",
    "GEAR",
    "SST",
    "CPUE",
    "SPECIES_GROUP"
]

tuna_model = tuna_model[cols]
bill_model = bill_model[cols]

# Combine
combined = pd.concat(
    [tuna_model, bill_model],
    ignore_index=True
)

# Valid observations only
combined = combined[
    (combined["CPUE"] > 0) &
    (combined["SST"].notna()) &
    (combined["GEAR"].notna())
].copy()

# Log target
combined["LOG_CPUE"] = np.log(combined["CPUE"])

# Seasonal features
combined["MONTH_SIN"] = np.sin(
    2 * np.pi * combined["MONTH_START"] / 12
)

combined["MONTH_COS"] = np.cos(
    2 * np.pi * combined["MONTH_START"] / 12
)

print("Combined rows:", len(combined))

print("\nSpecies groups:")
print(combined["SPECIES_GROUP"].value_counts())

print("\nUnique grounds:",
      combined["FISHING_GROUND_CODE"].nunique())

Combined rows: 498

Species groups:
SPECIES_GROUP
TUNA        290
BILLFISH    208
Name: count, dtype: int64

Unique grounds: 42

In [126]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# -----------------------------
# Time-based split
# -----------------------------
train = combined[combined["YEAR"] <= 2011].copy()
test = combined[combined["YEAR"].between(2012, 2014)].copy()

features = [
    "SST",
    "CENTER_LAT",
    "CENTER_LON",
    "MONTH_SIN",
    "MONTH_COS",
    "GEAR",
    "SPECIES_GROUP"
]

X_train = train[features]
y_train = train["LOG_CPUE"]

X_test = test[features]
y_test = test["LOG_CPUE"]

# -----------------------------
# Encode categorical features
# -----------------------------
categorical_features = ["GEAR", "SPECIES_GROUP"]
numeric_features = [
    "SST",
    "CENTER_LAT",
    "CENTER_LON",
    "MONTH_SIN",
    "MONTH_COS"
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "numeric",
            "passthrough",
            numeric_features
        )
    ]
)

# -----------------------------
# Random Forest
# -----------------------------
rf_model = Pipeline([
    ("preprocessor", preprocessor),
    (
        "model",
        RandomForestRegressor(
            n_estimators=400,
            max_depth=8,
            min_samples_leaf=3,
            random_state=42,
            n_jobs=-1
        )
    )
])

# Train
rf_model.fit(X_train, y_train)

# Predict
pred_log = rf_model.predict(X_test)

# Metrics
mae = mean_absolute_error(y_test, pred_log)
rmse = np.sqrt(mean_squared_error(y_test, pred_log))
r2 = r2_score(y_test, pred_log)

print("TRAINING ROWS:", len(train))
print("TEST ROWS:", len(test))

print("\nMODEL RESULTS")
print("----------------")
print("MAE :", round(mae, 4))
print("RMSE:", round(rmse, 4))
print("R²  :", round(r2, 4))

TRAINING ROWS: 414
TEST ROWS: 84

MODEL RESULTS
----------------
MAE : 1.0342
RMSE: 1.2849
R²  : 0.3916

In [127]:
def predict_top_10(year, month):
    """
    Predict and rank the 10 most productive fishing grounds
    for the requested year and month.
    """

    # Candidate grounds from our historical data
    candidates = combined[
        ["FISHING_GROUND_CODE", "CENTER_LAT", "CENTER_LON"]
    ].drop_duplicates("FISHING_GROUND_CODE").copy()

    # Keep grounds inside SST coverage
    candidates = candidates[
        candidates["CENTER_LAT"].between(2.5, 20.0) &
        candidates["CENTER_LON"].between(65.5, 95.5)
    ].copy()

    # Find SST for each candidate
    predictions = []

    for _, row in candidates.iterrows():

        month_data = ds.sel(
            time=ds.time.where(
                (ds.time.dt.year == year) &
                (ds.time.dt.month == month),
                drop=True
            )
        )

        if len(month_data.time) == 0:
            continue

        point = month_data["SST"].sel(
            latitude=row["CENTER_LAT"],
            longitude=row["CENTER_LON"],
            method="nearest"
        )

        sst_value = float(point.mean(skipna=True).values)

        if np.isnan(sst_value):
            continue

        # Predict for BOTH fisheries
        for species_group in ["TUNA", "BILLFISH"]:

            for gear in combined["GEAR"].unique():

                predictions.append({
                    "FISHING_GROUND_CODE":
                        row["FISHING_GROUND_CODE"],
                    "CENTER_LAT":
                        row["CENTER_LAT"],
                    "CENTER_LON":
                        row["CENTER_LON"],
                    "SST": sst_value,
                    "MONTH_SIN":
                        np.sin(2 * np.pi * month / 12),
                    "MONTH_COS":
                        np.cos(2 * np.pi * month / 12),
                    "GEAR": gear,
                    "SPECIES_GROUP":
                        species_group
                })

    prediction_df = pd.DataFrame(predictions)

    prediction_df["PRED_LOG_CPUE"] = rf_model.predict(
        prediction_df[features]
    )

    prediction_df["PRED_CPUE"] = np.exp(
        prediction_df["PRED_LOG_CPUE"]
    )

    # Average predictions across gear/species combinations
    top10 = (
        prediction_df
        .groupby(
            [
                "FISHING_GROUND_CODE",
                "CENTER_LAT",
                "CENTER_LON"
            ],
            as_index=False
        )
        .agg(
            PREDICTED_PRODUCTIVITY=("PRED_CPUE", "mean")
        )
        .sort_values(
            "PREDICTED_PRODUCTIVITY",
            ascending=False
        )
        .head(10)
        .reset_index(drop=True)
    )

    top10.insert(0, "RANK", range(1, len(top10) + 1))

    return top10

In [128]:
top10 = predict_top_10(2014, 7)

display(top10)

   RANK FISHING_GROUND_CODE  CENTER_LAT  CENTER_LON  PREDICTED_PRODUCTIVITY
0     1             5115071        15.5        71.5                0.000068
1     2             5115065        15.5        65.5                0.000067
2     3             5114067        14.5        67.5                0.000067
3     4             5115066        15.5        66.5                0.000067
4     5             6115065        17.5        67.5                0.000062
5     6             6110065        12.5        67.5                0.000060
6     7             5115070        15.5        70.5                0.000058
7     8             5110066        10.5        66.5                0.000054
8     9             5110065        10.5        65.5                0.000053
9    10             5119067        19.5        67.5                0.000052

In [129]:
# Actual observations from the held-out test period
actual = combined[
    (combined["YEAR"] == 2014) &
    (combined["MONTH_START"] == 7)
].copy()

# Average actual productivity per ground
actual_ground = (
    actual
    .groupby("FISHING_GROUND_CODE", as_index=False)
    .agg(
        ACTUAL_PRODUCTIVITY=("CPUE", "mean")
    )
    .sort_values(
        "ACTUAL_PRODUCTIVITY",
        ascending=False
    )
)

# Get predicted Top 10
predicted_ground = predict_top_10(2014, 7)

# Compare
actual_top10 = set(
    actual_ground.head(10)["FISHING_GROUND_CODE"]
)

predicted_top10 = set(
    predicted_ground["FISHING_GROUND_CODE"]
)

overlap = actual_top10 & predicted_top10

print("Actual grounds observed:", len(actual_ground))
print("Actual Top-10 grounds:", actual_top10)
print("\nPredicted Top-10 grounds:", predicted_top10)

print("\nTop-10 overlap:",
      len(overlap),
      "/",
      min(10, len(actual_top10)))

print("\nMatching grounds:")
print(sorted(overlap))

Actual grounds observed: 3
Actual Top-10 grounds: {'5110080', '5110070', '5105070'}

Predicted Top-10 grounds: {'5110065', '5115071', '5115070', '6115065', '5114067', '5115066', '5110066', '5119067', '6110065', '5115065'}

Top-10 overlap: 0 / 3

Matching grounds:
[]

In [130]:
# Check whether the actual July 2014 grounds were present in training

train_grounds = set(
    combined[combined["YEAR"] <= 2011]["FISHING_GROUND_CODE"]
)

actual_july = set(
    combined[
        (combined["YEAR"] == 2014) &
        (combined["MONTH_START"] == 7)
    ]["FISHING_GROUND_CODE"]
)

print("Actual July 2014 grounds:")
print(actual_july)

print("\nWere they seen during training?")
for g in sorted(actual_july):
    print(g, "->", g in train_grounds)

Actual July 2014 grounds:
{'5110080', '5110070', '5105070'}

Were they seen during training?
5105070 -> False
5110070 -> False
5110080 -> True

In [131]:
# Get predictions for all candidate grounds
pred_july = predict_top_10(2014, 7)

# Check whether the known actual ground made the Top 10
known_ground = "5110080"

print("Known ground:", known_ground)

if known_ground in set(pred_july["FISHING_GROUND_CODE"]):
    rank = pred_july.loc[
        pred_july["FISHING_GROUND_CODE"] == known_ground,
        "RANK"
    ].iloc[0]

    print("Predicted rank:", rank)
else:
    print("Known ground was NOT in predicted Top 10.")

Known ground: 5110080
Known ground was NOT in predicted Top 10.

In [132]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Time split
train = combined[combined["YEAR"] <= 2011].copy()
test = combined[combined["YEAR"].between(2012, 2014)].copy()

features = [
    "SST",
    "CENTER_LAT",
    "CENTER_LON",
    "MONTH_SIN",
    "MONTH_COS",
    "GEAR",
    "SPECIES_GROUP",
    "FISHING_GROUND_CODE"
]

X_train = train[features]
y_train = train["LOG_CPUE"]

X_test = test[features]
y_test = test["LOG_CPUE"]

categorical_features = [
    "GEAR",
    "SPECIES_GROUP",
    "FISHING_GROUND_CODE"
]

numeric_features = [
    "SST",
    "CENTER_LAT",
    "CENTER_LON",
    "MONTH_SIN",
    "MONTH_COS"
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "numeric",
            "passthrough",
            numeric_features
        )
    ]
)

rf_ground = Pipeline([
    ("preprocessor", preprocessor),
    (
        "model",
        RandomForestRegressor(
            n_estimators=500,
            max_depth=8,
            min_samples_leaf=3,
            random_state=42,
            n_jobs=-1
        )
    )
])

rf_ground.fit(X_train, y_train)

pred_log = rf_ground.predict(X_test)

mae = mean_absolute_error(y_test, pred_log)
rmse = np.sqrt(mean_squared_error(y_test, pred_log))
r2 = r2_score(y_test, pred_log)

print("TRAIN:", len(train))
print("TEST :", len(test))

print("\nGROUND-AWARE MODEL")
print("------------------")
print("MAE :", round(mae, 4))
print("RMSE:", round(rmse, 4))
print("R²  :", round(r2, 4))

TRAIN: 414
TEST : 84

GROUND-AWARE MODEL
------------------
MAE : 1.0316
RMSE: 1.2702
R²  : 0.4055

In [133]:
def predict_top_10_ground_aware(year, month):

    candidates = combined[
        ["FISHING_GROUND_CODE", "CENTER_LAT", "CENTER_LON"]
    ].drop_duplicates("FISHING_GROUND_CODE").copy()

    candidates = candidates[
        candidates["CENTER_LAT"].between(2.5, 20.0) &
        candidates["CENTER_LON"].between(65.5, 95.5)
    ].copy()

    month_data = ds.sel(
        time=ds.time.where(
            (ds.time.dt.year == year) &
            (ds.time.dt.month == month),
            drop=True
        )
    )

    if len(month_data.time) == 0:
        raise ValueError("No SST data available for this year/month.")

    predictions = []

    for _, row in candidates.iterrows():

        point = month_data["SST"].sel(
            latitude=row["CENTER_LAT"],
            longitude=row["CENTER_LON"],
            method="nearest"
        )

        sst_value = float(point.mean(skipna=True).values)

        if np.isnan(sst_value):
            continue

        for species_group in ["TUNA", "BILLFISH"]:

            for gear in combined["GEAR"].unique():

                predictions.append({
                    "FISHING_GROUND_CODE": row["FISHING_GROUND_CODE"],
                    "CENTER_LAT": row["CENTER_LAT"],
                    "CENTER_LON": row["CENTER_LON"],
                    "SST": sst_value,
                    "MONTH_SIN": np.sin(2 * np.pi * month / 12),
                    "MONTH_COS": np.cos(2 * np.pi * month / 12),
                    "GEAR": gear,
                    "SPECIES_GROUP": species_group
                })

    prediction_df = pd.DataFrame(predictions)

    prediction_df["PRED_LOG_CPUE"] = final_model.predict(
    prediction_df[features]

    )

    prediction_df["PRED_CPUE"] = np.exp(
        prediction_df["PRED_LOG_CPUE"]
    )

    top10 = (
        prediction_df
        .groupby(
            ["FISHING_GROUND_CODE",
             "CENTER_LAT",
             "CENTER_LON"],
            as_index=False
        )
        .agg(
            PREDICTED_PRODUCTIVITY=("PRED_CPUE", "mean")
        )
        .sort_values(
            "PREDICTED_PRODUCTIVITY",
            ascending=False
        )
        .head(10)
        .reset_index(drop=True)
    )

    top10.insert(0, "RANK", range(1, len(top10) + 1))

    return top10

In [140]:
top10 = predict_top_10_ground_aware(2014, 7)

display(top10)

   RANK FISHING_GROUND_CODE  CENTER_LAT  CENTER_LON  PREDICTED_PRODUCTIVITY
0     1             5115065   15.500000   65.500000                0.000065
1     2             5115066   15.500000   66.500000                0.000064
2     3             5114067   14.500000   67.500000                0.000063
3     4             5110065   10.500000   65.500000                0.000062
4     5             5110066   10.500000   66.500000                0.000062
5     6             5115071   15.500000   71.500000                0.000060
6     7             6110065   12.500000   67.500000                0.000060
7     8             6105070    7.500153   72.499889                0.000055
8     9             5115070   15.500000   70.500000                0.000055
9    10             5110070   10.500000   70.500000                0.000055

In [141]:
# ==========================================
# FINAL PRODUCTION MODEL
# Train on ALL available historical data
# ==========================================

X_all = combined[features]
y_all = combined["LOG_CPUE"]

final_model = Pipeline([
    ("preprocessor", preprocessor),
    (
        "model",
        RandomForestRegressor(
            n_estimators=600,
            max_depth=8,
            min_samples_leaf=3,
            random_state=42,
            n_jobs=-1
        )
    )
])

# FIT FINAL MODEL
final_model.fit(X_all, y_all)

print("FINAL MODEL FITTED")
print("-------------------")
print("Training observations:", len(combined))
print("Training years:",
      combined["YEAR"].min(),
      "to",
      combined["YEAR"].max())
print("Features:", features)

FINAL MODEL FITTED
-------------------
Training observations: 498
Training years: 2005 to 2014
Features: ['SST', 'CENTER_LAT', 'CENTER_LON', 'MONTH_SIN', 'MONTH_COS', 'GEAR', 'SPECIES_GROUP', 'FISHING_GROUND_CODE']

In [137]:
final_top10 = predict_top_10_ground_aware(2014, 7)

display(final_top10)

   RANK FISHING_GROUND_CODE  CENTER_LAT  CENTER_LON  PREDICTED_PRODUCTIVITY
0     1             5115065   15.500000   65.500000                0.000065
1     2             5115066   15.500000   66.500000                0.000064
2     3             5114067   14.500000   67.500000                0.000063
3     4             5110065   10.500000   65.500000                0.000062
4     5             5110066   10.500000   66.500000                0.000062
5     6             5115071   15.500000   71.500000                0.000060
6     7             6110065   12.500000   67.500000                0.000060
7     8             6105070    7.500153   72.499889                0.000055
8     9             5115070   15.500000   70.500000                0.000055
9    10             5110070   10.500000   70.500000                0.000055

In [138]:
import joblib
import os

model_path = "/content/drive/MyDrive/DATASETS/fishing_ground_model_final.joblib"

joblib.dump(
    {
        "model": final_model,
        "features": features,
        "training_years": (2005, 2014),
        "training_rows": len(combined),
        "target": "LOG_CPUE",
        "description": "Indian fishing-ground productivity ranking model using Tropical Tuna + Billfish, SST, season, location, gear and fishing-ground history"
    },
    model_path
)

print("MODEL SAVED")
print(model_path)
print("Size:", round(os.path.getsize(model_path) / 1024**2, 2), "MB")

MODEL SAVED
/content/drive/MyDrive/DATASETS/fishing_ground_model_final.joblib
Size: 5.27 MB

In [139]:
print("final_model" in globals())

True

In [136]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline

features = [
    "SST",
    "CENTER_LAT",
    "CENTER_LON",
    "MONTH_SIN",
    "MONTH_COS",
    "GEAR",
    "SPECIES_GROUP",
    "FISHING_GROUND_CODE"
]

X = combined[features]
y = combined["LOG_CPUE"]

categorical_features = [
    "GEAR",
    "SPECIES_GROUP",
    "FISHING_GROUND_CODE"
]

numeric_features = [
    "SST",
    "CENTER_LAT",
    "CENTER_LON",
    "MONTH_SIN",
    "MONTH_COS"
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "num",
            "passthrough",
            numeric_features
        )
    ]
)

final_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=600,
        max_depth=8,
        min_samples_leaf=3,
        random_state=42,
        n_jobs=-1
    ))
])

final_model.fit(X, y)

print("✅ Final model trained successfully")
print("Training rows:", len(combined))
print("Training years:", combined["YEAR"].min(), "to", combined["YEAR"].max())

✅ Final model trained successfully
Training rows: 498
Training years: 2005 to 2014